use std::slice::from_raw_parts;

use anyhow::Result;
use raw_cstr::raw_cstr;
use simics_api_sys::{
    A20_INTERFACE, ABS_POINTER_ACTIVATE_INTERFACE, ABS_POINTER_INTERFACE,
    ADDRESS_PROFILER_INTERFACE, APIC_CPU_INTERFACE, ARM_AVIC_INTERFACE, ARM_COPROCESSOR_INTERFACE,
    BANK_AFTER_READ_INTERFACE, BANK_AFTER_WRITE_INTERFACE, BANK_BEFORE_READ_INTERFACE,
    BANK_BEFORE_WRITE_INTERFACE, BRANCH_ARC_INTERFACE, BREAKPOINT_CHANGE_INTERFACE,
    BREAKPOINT_INTERFACE, BREAKPOINT_MANAGER_INTERFACE, BREAKPOINT_QUERY_INTERFACE,
    BREAKPOINT_QUERY_V2_INTERFACE, BREAKPOINT_TRIGGER_INTERFACE, BREAKPOINT_TYPE_INTERFACE,
    BREAKPOINT_TYPE_PROVIDER_INTERFACE, BREAK_STRINGS_V2_INTERFACE, BRIDGE_INTERFACE,
    CACHE_CONTROL_INTERFACE, CALLBACK_INFO_INTERFACE, CELL_INSPECTION_INTERFACE,
    CHECKPOINT_INTERFACE, COMPONENT_CONNECTOR_INTERFACE, COMPONENT_INTERFACE,
    CONCURRENCY_GROUP_INTERFACE, CONCURRENCY_MODE_INTERFACE, CONNECTOR_INTERFACE,
    CONTEXT_HANDLER_INTERFACE, CON_INPUT_CODE_INTERFACE, CON_INPUT_INTERFACE, CO_EXECUTE_INTERFACE,
    CPU_CACHED_INSTRUCTION_INTERFACE, CPU_CACHED_STREAM_INTERFACE, CPU_EXCEPTION_QUERY_INTERFACE,
    CPU_INSTRUCTION_DECODER_INTERFACE, CPU_INSTRUCTION_QUERY_INTERFACE,
    CPU_INSTRUMENTATION_SUBSCRIBE_INTERFACE, CPU_MEMORY_QUERY_INTERFACE, CYCLE_CONTROL_INTERFACE,
    CYCLE_EVENT_INTERFACE, CYCLE_INTERFACE, DATA_PROFILER_INTERFACE, DEBUG_NOTIFICATION_INTERFACE,
    DEBUG_QUERY_INTERFACE, DEBUG_SETUP_INTERFACE, DEBUG_STEP_INTERFACE,
    DEBUG_SYMBOL_FILE_INTERFACE, DEBUG_SYMBOL_INTERFACE, DESCRIBE_REGISTERS_INTERFACE,
    DEVICE_IDENTIFICATION_INTERFACE, DIRECT_MEMORY_FLUSH_INTERFACE, DIRECT_MEMORY_INTERFACE,
    DIRECT_MEMORY_LOOKUP_INTERFACE, DIRECT_MEMORY_LOOKUP_V2_INTERFACE,
    DIRECT_MEMORY_TAGS_INTERFACE, DIRECT_MEMORY_UPDATE_INTERFACE, DISASSEMBLE_INTERFACE,
    DISK_COMPONENT_INTERFACE, EVENT_DELTA_INTERFACE, EVENT_HANDLER_INTERFACE, EXCEPTION_INTERFACE,
    EXECUTE_CONTROL_INTERFACE, EXECUTE_INTERFACE, EXEC_TRACE_INTERFACE, EXTENDED_SERIAL_INTERFACE,
    FIREWIRE_BUS_INTERFACE, FIREWIRE_DEVICE_INTERFACE, FMN_STATION_CONTROL_INTERFACE,
    FMN_STATION_CONTROL_V2_INTERFACE, FREERUN_INTERFACE, FREQUENCY_INTERFACE,
    FREQUENCY_LISTENER_INTERFACE, GFX_BREAK_INTERFACE, GFX_CONSOLE_BACKEND_INTERFACE,
    GFX_CON_INTERFACE, HAP_LISTEN_INTERFACE, HOST_SERIAL_INTERFACE, I2C_BRIDGE_INTERFACE,
    I2C_BUS_INTERFACE, I2C_DEVICE_INTERFACE, I2C_LINK_INTERFACE, I2C_MASTER_INTERFACE,
    I2C_MASTER_V2_INTERFACE, I2C_SLAVE_INTERFACE, I2C_SLAVE_V2_INTERFACE, I3C_DAA_SNOOP_INTERFACE,
    I3C_MASTER_INTERFACE, I3C_SLAVE_INTERFACE, I8051_INTERRUPT_INTERFACE, I8051_TIMER_INTERFACE,
    IMAGE_INTERFACE, IMAGE_SNOOP_INTERFACE, INSTRUCTION_FETCH_INTERFACE,
    INSTRUMENTATION_CONNECTION_INTERFACE, INSTRUMENTATION_FILTER_MASTER_INTERFACE,
    INSTRUMENTATION_FILTER_SLAVE_INTERFACE, INSTRUMENTATION_FILTER_STATUS_INTERFACE,
    INSTRUMENTATION_ORDER_INTERFACE, INSTRUMENTATION_TOOL_INTERFACE, INTERRUPT_ACK_INTERFACE,
    INTERRUPT_CPU_INTERFACE, INT_REGISTER_INTERFACE, IO_MEMORY_INTERFACE,
    KEYBOARD_CONSOLE_INTERFACE, KEYBOARD_INTERFACE, LINEAR_IMAGE_INTERFACE, MAP_DEMAP_INTERFACE,
    MEMORY_PROFILER_INTERFACE, MEMORY_SPACE_INTERFACE, MIPS_COPROCESSOR_INTERFACE,
    MIPS_EIC_INTERFACE, MIPS_EXCEPTION_QUERY_INTERFACE, MIPS_INTERFACE, MIPS_ITE_INTERFACE,
    MOUSE_INTERFACE, MS1553_LINK_INTERFACE, MS1553_TERMINAL_INTERFACE,
    MULTI_LEVEL_SIGNAL_INTERFACE, NIOS_EIC_INTERFACE, NIOS_INTERFACE, OPCODE_INFO_INTERFACE,
    OSA_COMPONENT_INTERFACE, OSA_CONTROL_INTERFACE, OSA_CONTROL_V2_INTERFACE,
    OSA_MACHINE_NOTIFICATION_INTERFACE, OSA_MACHINE_QUERY_INTERFACE, OSA_MAPPER_ADMIN_INTERFACE,
    OSA_MAPPER_CONTROL_INTERFACE, OSA_MAPPER_QUERY_INTERFACE, OSA_MICRO_CHECKPOINT_INTERFACE,
    OSA_NODE_PATH_INTERFACE, OSA_NODE_TREE_ADMIN_INTERFACE, OSA_NODE_TREE_NOTIFICATION_INTERFACE,
    OSA_NODE_TREE_QUERY_INTERFACE, OSA_PARAMETERS_INTERFACE, OSA_TRACKER_COMPONENT_INTERFACE,
    OSA_TRACKER_CONTROL_INTERFACE, OSA_TRACKER_STATE_ADMIN_INTERFACE,
    OSA_TRACKER_STATE_QUERY_INTERFACE, PACKET_INTERFACE, PCIE_DEVICE_INTERFACE, PCIE_MAP_INTERFACE,
    PCIE_PORT_CONTROL_INTERFACE, PCI_BRIDGE_INTERFACE, PCI_BUS_INTERFACE, PCI_DEVICE_INTERFACE,
    PCI_DOWNSTREAM_INTERFACE, PCI_EXPRESS_HOTPLUG_INTERFACE, PCI_EXPRESS_INTERFACE,
    PCI_INTERRUPT_INTERFACE, PCI_MULTI_FUNCTION_DEVICE_INTERFACE, PCI_UPSTREAM_INTERFACE,
    PCI_UPSTREAM_OPERATION_INTERFACE, PMR_INTERFACE, POOL_PROTECT_INTERFACE, PORT_SPACE_INTERFACE,
    PPC_INTERFACE, PREFERENCE_INTERFACE, PROBE_CACHE_INTERFACE, PROBE_INDEX_INTERFACE,
    PROBE_INTERFACE, PROBE_SUBSCRIBE_INTERFACE, PROCESSOR_CLI_INTERFACE,
    PROCESSOR_ENDIAN_INTERFACE, PROCESSOR_GUI_INTERFACE, PROCESSOR_INFO_INTERFACE,
    PROCESSOR_INFO_V2_INTERFACE, PULSE_INTERFACE, RAM_ACCESS_SUBSCRIBE_INTERFACE,
    RAPIDIO_V3_INTERFACE, RAPIDIO_V4_INTERFACE, RAPIDIO_V5_INTERFACE, RECORDED_INTERFACE,
    RECORDER_INTERFACE, REGISTER_BREAKPOINT_INTERFACE, RISCV_COPROCESSOR_INTERFACE,
    RS232_CONSOLE_INTERFACE, RS232_DEVICE_INTERFACE, SATA_INTERFACE, SCALAR_TIME_INTERFACE,
    SCALE_FACTOR_LISTENER_INTERFACE, SCREENSHOT_INTERFACE, SERIAL_CONSOLE_FRONTEND_INTERFACE,
    SERIAL_DEVICE_INTERFACE, SIGNAL_INTERFACE, SIMPLE_DISPATCHER_INTERFACE,
    SIMPLE_INTERRUPT_INTERFACE, SIMULATOR_CACHE_INTERFACE, SPARC_V8_ECC_FAULT_INJECTION_INTERFACE,
    SPARC_V8_INTERFACE, SPR_INTERFACE, STALL_INTERFACE, STEP_CYCLE_RATIO_INTERFACE,
    STEP_INFO_INTERFACE, STEP_INTERFACE, SYNCHRONOUS_MODE_INTERFACE, TABLE_INTERFACE,
    TELNET_CONNECTION_INTERFACE, TEMPORAL_STATE_INTERFACE, TRANSACTION_INTERFACE,
    TRANSACTION_TRANSLATOR_INTERFACE, TRANSLATE_INTERFACE, TRANSLATION_FLUSH_INTERFACE,
    TRANSLATOR_INTERFACE, UINT64_STATE_INTERFACE, USB_DEVICE_INTERFACE, USB_INTERFACE,
    VECTORED_INTERRUPT_INTERFACE, VECTORED_INTERRUPT_SOURCE_INTERFACE, VGA_TEXT_INFO_INTERFACE,
    VGA_TEXT_UPDATE_INTERFACE, VGA_UPDATE_INTERFACE, VIRTUAL_DATA_BREAKPOINT_INTERFACE,
    VMP_INTERFACE, VNC_SERVER_INTERFACE, X86_ADDRESS_QUERY_INTERFACE, X86_CACHE_FLUSH_INTERFACE,
    X86_CPUID_INTERFACE, X86_CPUID_QUERY_INTERFACE, X86_CSTATE_INTERFACE,
    X86_CSTATE_NOTIFICATION_INTERFACE, X86_EXCEPTION_INTERFACE, X86_EXCEPTION_QUERY_INTERFACE,
    X86_INSTRUCTION_QUERY_INTERFACE, X86_INTERFACE, X86_MEMORY_ACCESS_INTERFACE,
    X86_MEMORY_OPERATION_INTERFACE, X86_MSR_INTERFACE, X86_PKG_CSTATE_INTERFACE,
    X86_REG_ACCESS_INTERFACE, X86_SMM_INTERFACE, X86_SMM_STATE_INTERFACE, X86_TLB_INTERFACE,
    X86_TLB_V2_INTERFACE, X86_TLB_V3_INTERFACE, X86_VMP_CONTROL_INTERFACE, XED_ACCESS_INTERFACE,
    XTENSA_EXPORT_STATE_INTERFACE, XTENSA_IMPORT_WIRE_INTERFACE, XTENSA_INPUT_QUEUE_INTERFACE,
    XTENSA_LOOKUP_INTERFACE, XTENSA_OUTPUT_QUEUE_INTERFACE, XTENSA_TIE_EXPORT_STATE_INTERFACE,
    XTENSA_TIE_IMPORT_WIRE_INTERFACE, XTENSA_TIE_INPUT_QUEUE_INTERFACE,
    XTENSA_TIE_LOOKUP_INTERFACE, XTENSA_TIE_OUTPUT_QUEUE_INTERFACE,
};

/// Available interfaces
pub enum Interface {
    A20,
    AbsPointer,
    AbsPointerActivate,
    AddressProfiler,
    ApicCpu,
    ArmAvic,
    ArmCoprocessor,
    BankAfterRead,
    BankAfterWrite,
    BankBeforeRead,
    BankBeforeWrite,
    BranchArc,
    BreakStringsV2,
    Breakpoint,
    BreakpointChange,
    BreakpointManager,
    BreakpointQuery,
    BreakpointQueryV2,
    BreakpointTrigger,
    BreakpointType,
    BreakpointTypeProvider,
    Bridge,
    CacheControl,
    CallbackInfo,
    CellInspection,
    Checkpoint,
    CoExecute,
    Component,
    ComponentConnector,
    ConInput,
    ConInputCode,
    ConcurrencyGroup,
    ConcurrencyMode,
    Connector,
    ContextHandler,
    CpuCachedInstruction,
    CpuCachedStream,
    CpuExceptionQuery,
    CpuInstructionDecoder,
    CpuInstructionQuery,
    CpuInstrumentationSubscribe,
    CpuMemoryQuery,
    Cycle,
    CycleControl,
    CycleEvent,
    DataProfiler,
    DebugNotification,
    DebugQuery,
    DebugSetup,
    DebugStep,
    DebugSymbol,
    DebugSymbolFile,
    DescribeRegisters,
    DeviceIdentification,
    DirectMemory,
    DirectMemoryFlush,
    DirectMemoryLookup,
    DirectMemoryLookupInterfaceV2,
    DirectMemoryTags,
    DirectMemoryUpdate,
    Disassemble,
    DiskComponent,
    EventDelta,
    EventHandler,
    Exception,
    ExecTrace,
    Execute,
    ExecuteControl,
    ExtendedSerial,
    FirewireBus,
    FirewireDevice,
    FmnStationControl,
    FmnStationControlV2,
    Freerun,
    Frequency,
    FrequencyListener,
    GfxBreak,
    GfxCon,
    GfxConsoleBackend,
    HapListen,
    HostSerial,
    I2cBridge,
    I2cBus,
    I2cDevice,
    I2cLink,
    I2cMaster,
    I2cMasterV2,
    I2cSlave,
    I2cSlaveV2,
    I3cDaaSnoop,
    I3cMaster,
    I3cSlave,
    I8051Interrupt,
    I8051Timer,
    Image,
    ImageSnoop,
    InstructionFetch,
    InstrumentationConnection,
    InstrumentationFilterMaster,
    InstrumentationFilterSlave,
    InstrumentationFilterStatus,
    InstrumentationOrder,
    InstrumentationTool,
    IntRegister,
    InterruptAck,
    InterruptCpu,
    IoMemory,
    Keyboard,
    KeyboardConsole,
    LinearImage,
    MapDemap,
    MemoryProfiler,
    MemorySpace,
    Mips,
    MipsCoprocessor,
    MipsEic,
    MipsExceptionQuery,
    MipsIte,
    Mouse,
    Ms1553Link,
    Ms1553Terminal,
    MultiLevelSignal,
    Nios,
    NiosEic,
    OpcodeInfo,
    OsaComponent,
    OsaControl,
    OsaControlV2,
    OsaMachineNotification,
    OsaMachineQuery,
    OsaMapperAdmin,
    OsaMapperControl,
    OsaMapperQuery,
    OsaMicroCheckpoint,
    OsaNodePath,
    OsaNodeTreeAdmin,
    OsaNodeTreeNotification,
    OsaNodeTreeQuery,
    OsaParameters,
    OsaTrackerComponent,
    OsaTrackerControl,
    OsaTrackerStateAdmin,
    OsaTrackerStateQuery,
    Packet,
    PciBridge,
    PciBus,
    PciDevice,
    PciDownstream,
    PciExpress,
    PciExpressHotplug,
    PciInterrupt,
    PciMultiFunctionDevice,
    PciUpstream,
    PciUpstreamOperation,
    PcieDevice,
    PcieMap,
    PciePortControl,
    Pmr,
    PoolProtect,
    PortSpace,
    Ppc,
    Preference,
    Probe,
    ProbeCache,
    ProbeIndex,
    ProbeSubscribe,
    ProcessorCli,
    ProcessorEndian,
    ProcessorGui,
    ProcessorInfo,
    ProcessorInfoV2,
    Pulse,
    RamAccessSubscribe,
    RapidioV3,
    RapidioV4,
    RapidioV5,
    Recorded,
    Recorder,
    RegisterBreakpoint,
    RiscvCoprocessor,
    Rs232Console,
    Rs232Device,
    Sata,
    ScalarTime,
    ScaleFactorListener,
    Screenshot,
    SerialConsoleFrontend,
    SerialDevice,
    Signal,
    SimpleDispatcher,
    SimpleInterrupt,
    SimulatorCache,
    SparcV8,
    SparcV8EccFaultInjection,
    Spr,
    Stall,
    Step,
    StepCycleRatio,
    StepInfo,
    SynchronousMode,
    Table,
    TelnetConnection,
    TemporalState,
    Transaction,
    TransactionTranslator,
    Translate,
    TranslationFlush,
    Translator,
    Uint64State,
    Usb,
    UsbDevice,
    VectoredInterrupt,
    VectoredInterruptSource,
    VgaTextInfo,
    VgaTextUpdate,
    VgaUpdate,
    VirtualDataBreakpoint,
    Vmp,
    VncServer,
    X86,
    X86AddressQuery,
    X86CacheFlush,
    X86Cpuid,
    X86CpuidQuery,
    X86Cstate,
    X86CstateNotification,
    X86Exception,
    X86ExceptionQuery,
    X86InstructionQuery,
    X86MemoryAccess,
    X86MemoryOperation,
    X86Msr,
    X86PkgCstate,
    X86RegAccess,
    X86Smm,
    X86SmmState,
    X86Tlb,
    X86TlbV2,
    X86TlbV3,
    X86VmpControl,
    XedAccess,
    XtensaExportState,
    XtensaImportWire,
    XtensaInputQueue,
    XtensaLookup,
    XtensaOutputQueue,
    XtensaTieExportState,
    XtensaTieImportWire,
    XtensaTieInputQueue,
    XtensaTieLookup,
    XtensaTieOutputQueue,
    Other(String),
}

impl Interface {
    /// Get the interface name as a null-terminated character slice
    pub fn try_as_slice(&self) -> Result<&'static [u8]> {
        Ok(match self {
            Interface::A20 => A20_INTERFACE,
            Interface::AbsPointer => ABS_POINTER_INTERFACE,
            Interface::AbsPointerActivate => ABS_POINTER_ACTIVATE_INTERFACE,
            Interface::AddressProfiler => ADDRESS_PROFILER_INTERFACE,
            Interface::ApicCpu => APIC_CPU_INTERFACE,
            Interface::ArmAvic => ARM_AVIC_INTERFACE,
            Interface::ArmCoprocessor => ARM_COPROCESSOR_INTERFACE,
            Interface::BankAfterRead => BANK_AFTER_READ_INTERFACE,
            Interface::BankAfterWrite => BANK_AFTER_WRITE_INTERFACE,
            Interface::BankBeforeRead => BANK_BEFORE_READ_INTERFACE,
            Interface::BankBeforeWrite => BANK_BEFORE_WRITE_INTERFACE,
            Interface::BranchArc => BRANCH_ARC_INTERFACE,
            Interface::BreakStringsV2 => BREAK_STRINGS_V2_INTERFACE,
            Interface::Breakpoint => BREAKPOINT_INTERFACE,
            Interface::BreakpointChange => BREAKPOINT_CHANGE_INTERFACE,
            Interface::BreakpointManager => BREAKPOINT_MANAGER_INTERFACE,
            Interface::BreakpointQuery => BREAKPOINT_QUERY_INTERFACE,
            Interface::BreakpointQueryV2 => BREAKPOINT_QUERY_V2_INTERFACE,
            Interface::BreakpointTrigger => BREAKPOINT_TRIGGER_INTERFACE,
            Interface::BreakpointType => BREAKPOINT_TYPE_INTERFACE,
            Interface::BreakpointTypeProvider => BREAKPOINT_TYPE_PROVIDER_INTERFACE,
            Interface::Bridge => BRIDGE_INTERFACE,
            Interface::CacheControl => CACHE_CONTROL_INTERFACE,
            Interface::CallbackInfo => CALLBACK_INFO_INTERFACE,
            Interface::CellInspection => CELL_INSPECTION_INTERFACE,
            Interface::Checkpoint => CHECKPOINT_INTERFACE,
            Interface::CoExecute => CO_EXECUTE_INTERFACE,
            Interface::Component => COMPONENT_INTERFACE,
            Interface::ComponentConnector => COMPONENT_CONNECTOR_INTERFACE,
            Interface::ConInput => CON_INPUT_INTERFACE,
            Interface::ConInputCode => CON_INPUT_CODE_INTERFACE,
            Interface::ConcurrencyGroup => CONCURRENCY_GROUP_INTERFACE,
            Interface::ConcurrencyMode => CONCURRENCY_MODE_INTERFACE,
            Interface::Connector => CONNECTOR_INTERFACE,
            Interface::ContextHandler => CONTEXT_HANDLER_INTERFACE,
            Interface::CpuCachedInstruction => CPU_CACHED_INSTRUCTION_INTERFACE,
            Interface::CpuCachedStream => CPU_CACHED_STREAM_INTERFACE,
            Interface::CpuExceptionQuery => CPU_EXCEPTION_QUERY_INTERFACE,
            Interface::CpuInstructionDecoder => CPU_INSTRUCTION_DECODER_INTERFACE,
            Interface::CpuInstructionQuery => CPU_INSTRUCTION_QUERY_INTERFACE,
            Interface::CpuInstrumentationSubscribe => CPU_INSTRUMENTATION_SUBSCRIBE_INTERFACE,
            Interface::CpuMemoryQuery => CPU_MEMORY_QUERY_INTERFACE,
            Interface::Cycle => CYCLE_INTERFACE,
            Interface::CycleControl => CYCLE_CONTROL_INTERFACE,
            Interface::CycleEvent => CYCLE_EVENT_INTERFACE,
            Interface::DataProfiler => DATA_PROFILER_INTERFACE,
            Interface::DebugNotification => DEBUG_NOTIFICATION_INTERFACE,
            Interface::DebugQuery => DEBUG_QUERY_INTERFACE,
            Interface::DebugSetup => DEBUG_SETUP_INTERFACE,
            Interface::DebugStep => DEBUG_STEP_INTERFACE,
            Interface::DebugSymbol => DEBUG_SYMBOL_INTERFACE,
            Interface::DebugSymbolFile => DEBUG_SYMBOL_FILE_INTERFACE,
            Interface::DescribeRegisters => DESCRIBE_REGISTERS_INTERFACE,
            Interface::DeviceIdentification => DEVICE_IDENTIFICATION_INTERFACE,
            Interface::DirectMemory => DIRECT_MEMORY_INTERFACE,
            Interface::DirectMemoryFlush => DIRECT_MEMORY_FLUSH_INTERFACE,
            Interface::DirectMemoryLookup => DIRECT_MEMORY_LOOKUP_INTERFACE,
            Interface::DirectMemoryLookupInterfaceV2 => DIRECT_MEMORY_LOOKUP_V2_INTERFACE,
            Interface::DirectMemoryTags => DIRECT_MEMORY_TAGS_INTERFACE,
            Interface::DirectMemoryUpdate => DIRECT_MEMORY_UPDATE_INTERFACE,
            Interface::Disassemble => DISASSEMBLE_INTERFACE,
            Interface::DiskComponent => DISK_COMPONENT_INTERFACE,
            Interface::EventDelta => EVENT_DELTA_INTERFACE,
            Interface::EventHandler => EVENT_HANDLER_INTERFACE,
            Interface::Exception => EXCEPTION_INTERFACE,
            Interface::ExecTrace => EXEC_TRACE_INTERFACE,
            Interface::Execute => EXECUTE_INTERFACE,
            Interface::ExecuteControl => EXECUTE_CONTROL_INTERFACE,
            Interface::ExtendedSerial => EXTENDED_SERIAL_INTERFACE,
            Interface::FirewireBus => FIREWIRE_BUS_INTERFACE,
            Interface::FirewireDevice => FIREWIRE_DEVICE_INTERFACE,
            Interface::FmnStationControl => FMN_STATION_CONTROL_INTERFACE,
            Interface::FmnStationControlV2 => FMN_STATION_CONTROL_V2_INTERFACE,
            Interface::Freerun => FREERUN_INTERFACE,
            Interface::Frequency => FREQUENCY_INTERFACE,
            Interface::FrequencyListener => FREQUENCY_LISTENER_INTERFACE,
            Interface::GfxBreak => GFX_BREAK_INTERFACE,
            Interface::GfxCon => GFX_CON_INTERFACE,
            Interface::GfxConsoleBackend => GFX_CONSOLE_BACKEND_INTERFACE,
            Interface::HapListen => HAP_LISTEN_INTERFACE,
            Interface::HostSerial => HOST_SERIAL_INTERFACE,
            Interface::I2cBridge => I2C_BRIDGE_INTERFACE,
            Interface::I2cBus => I2C_BUS_INTERFACE,
            Interface::I2cDevice => I2C_DEVICE_INTERFACE,
            Interface::I2cLink => I2C_LINK_INTERFACE,
            Interface::I2cMaster => I2C_MASTER_INTERFACE,
            Interface::I2cMasterV2 => I2C_MASTER_V2_INTERFACE,
            Interface::I2cSlave => I2C_SLAVE_INTERFACE,
            Interface::I2cSlaveV2 => I2C_SLAVE_V2_INTERFACE,
            Interface::I3cDaaSnoop => I3C_DAA_SNOOP_INTERFACE,
            Interface::I3cMaster => I3C_MASTER_INTERFACE,
            Interface::I3cSlave => I3C_SLAVE_INTERFACE,
            Interface::I8051Interrupt => I8051_INTERRUPT_INTERFACE,
            Interface::I8051Timer => I8051_TIMER_INTERFACE,
            Interface::Image => IMAGE_INTERFACE,
            Interface::ImageSnoop => IMAGE_SNOOP_INTERFACE,
            Interface::InstructionFetch => INSTRUCTION_FETCH_INTERFACE,
            Interface::InstrumentationConnection => INSTRUMENTATION_CONNECTION_INTERFACE,
            Interface::InstrumentationFilterMaster => INSTRUMENTATION_FILTER_MASTER_INTERFACE,
            Interface::InstrumentationFilterSlave => INSTRUMENTATION_FILTER_SLAVE_INTERFACE,
            Interface::InstrumentationFilterStatus => INSTRUMENTATION_FILTER_STATUS_INTERFACE,
            Interface::InstrumentationOrder => INSTRUMENTATION_ORDER_INTERFACE,
            Interface::InstrumentationTool => INSTRUMENTATION_TOOL_INTERFACE,
            Interface::IntRegister => INT_REGISTER_INTERFACE,
            Interface::InterruptAck => INTERRUPT_ACK_INTERFACE,
            Interface::InterruptCpu => INTERRUPT_CPU_INTERFACE,
            Interface::IoMemory => IO_MEMORY_INTERFACE,
            Interface::Keyboard => KEYBOARD_INTERFACE,
            Interface::KeyboardConsole => KEYBOARD_CONSOLE_INTERFACE,
            Interface::LinearImage => LINEAR_IMAGE_INTERFACE,
            Interface::MapDemap => MAP_DEMAP_INTERFACE,
            Interface::MemoryProfiler => MEMORY_PROFILER_INTERFACE,
            Interface::MemorySpace => MEMORY_SPACE_INTERFACE,
            Interface::Mips => MIPS_INTERFACE,
            Interface::MipsCoprocessor => MIPS_COPROCESSOR_INTERFACE,
            Interface::MipsEic => MIPS_EIC_INTERFACE,
            Interface::MipsExceptionQuery => MIPS_EXCEPTION_QUERY_INTERFACE,
            Interface::MipsIte => MIPS_ITE_INTERFACE,
            Interface::Mouse => MOUSE_INTERFACE,
            Interface::Ms1553Link => MS1553_LINK_INTERFACE,
            Interface::Ms1553Terminal => MS1553_TERMINAL_INTERFACE,
            Interface::MultiLevelSignal => MULTI_LEVEL_SIGNAL_INTERFACE,
            Interface::Nios => NIOS_INTERFACE,
            Interface::NiosEic => NIOS_EIC_INTERFACE,
            Interface::OpcodeInfo => OPCODE_INFO_INTERFACE,
            Interface::OsaComponent => OSA_COMPONENT_INTERFACE,
            Interface::OsaControl => OSA_CONTROL_INTERFACE,
            Interface::OsaControlV2 => OSA_CONTROL_V2_INTERFACE,
            Interface::OsaMachineNotification => OSA_MACHINE_NOTIFICATION_INTERFACE,
            Interface::OsaMachineQuery => OSA_MACHINE_QUERY_INTERFACE,
            Interface::OsaMapperAdmin => OSA_MAPPER_ADMIN_INTERFACE,
            Interface::OsaMapperControl => OSA_MAPPER_CONTROL_INTERFACE,
            Interface::OsaMapperQuery => OSA_MAPPER_QUERY_INTERFACE,
            Interface::OsaMicroCheckpoint => OSA_MICRO_CHECKPOINT_INTERFACE,
            Interface::OsaNodePath => OSA_NODE_PATH_INTERFACE,
            Interface::OsaNodeTreeAdmin => OSA_NODE_TREE_ADMIN_INTERFACE,
            Interface::OsaNodeTreeNotification => OSA_NODE_TREE_NOTIFICATION_INTERFACE,
            Interface::OsaNodeTreeQuery => OSA_NODE_TREE_QUERY_INTERFACE,
            Interface::OsaParameters => OSA_PARAMETERS_INTERFACE,
            Interface::OsaTrackerComponent => OSA_TRACKER_COMPONENT_INTERFACE,
            Interface::OsaTrackerControl => OSA_TRACKER_CONTROL_INTERFACE,
            Interface::OsaTrackerStateAdmin => OSA_TRACKER_STATE_ADMIN_INTERFACE,
            Interface::OsaTrackerStateQuery => OSA_TRACKER_STATE_QUERY_INTERFACE,
            Interface::Packet => PACKET_INTERFACE,
            Interface::PciBridge => PCI_BRIDGE_INTERFACE,
            Interface::PciBus => PCI_BUS_INTERFACE,
            Interface::PciDevice => PCI_DEVICE_INTERFACE,
            Interface::PciDownstream => PCI_DOWNSTREAM_INTERFACE,
            Interface::PciExpress => PCI_EXPRESS_INTERFACE,
            Interface::PciExpressHotplug => PCI_EXPRESS_HOTPLUG_INTERFACE,
            Interface::PciInterrupt => PCI_INTERRUPT_INTERFACE,
            Interface::PciMultiFunctionDevice => PCI_MULTI_FUNCTION_DEVICE_INTERFACE,
            Interface::PciUpstream => PCI_UPSTREAM_INTERFACE,
            Interface::PciUpstreamOperation => PCI_UPSTREAM_OPERATION_INTERFACE,
            Interface::PcieDevice => PCIE_DEVICE_INTERFACE,
            Interface::PcieMap => PCIE_MAP_INTERFACE,
            Interface::PciePortControl => PCIE_PORT_CONTROL_INTERFACE,
            Interface::Pmr => PMR_INTERFACE,
            Interface::PoolProtect => POOL_PROTECT_INTERFACE,
            Interface::PortSpace => PORT_SPACE_INTERFACE,
            Interface::Ppc => PPC_INTERFACE,
            Interface::Preference => PREFERENCE_INTERFACE,
            Interface::Probe => PROBE_INTERFACE,
            Interface::ProbeCache => PROBE_CACHE_INTERFACE,
            Interface::ProbeIndex => PROBE_INDEX_INTERFACE,
            Interface::ProbeSubscribe => PROBE_SUBSCRIBE_INTERFACE,
            Interface::ProcessorCli => PROCESSOR_CLI_INTERFACE,
            Interface::ProcessorEndian => PROCESSOR_ENDIAN_INTERFACE,
            Interface::ProcessorGui => PROCESSOR_GUI_INTERFACE,
            Interface::ProcessorInfo => PROCESSOR_INFO_INTERFACE,
            Interface::ProcessorInfoV2 => PROCESSOR_INFO_V2_INTERFACE,
            Interface::Pulse => PULSE_INTERFACE,
            Interface::RamAccessSubscribe => RAM_ACCESS_SUBSCRIBE_INTERFACE,
            Interface::RapidioV3 => RAPIDIO_V3_INTERFACE,
            Interface::RapidioV4 => RAPIDIO_V4_INTERFACE,
            Interface::RapidioV5 => RAPIDIO_V5_INTERFACE,
            Interface::Recorded => RECORDED_INTERFACE,
            Interface::Recorder => RECORDER_INTERFACE,
            Interface::RegisterBreakpoint => REGISTER_BREAKPOINT_INTERFACE,
            Interface::RiscvCoprocessor => RISCV_COPROCESSOR_INTERFACE,
            Interface::Rs232Console => RS232_CONSOLE_INTERFACE,
            Interface::Rs232Device => RS232_DEVICE_INTERFACE,
            Interface::Sata => SATA_INTERFACE,
            Interface::ScalarTime => SCALAR_TIME_INTERFACE,
            Interface::ScaleFactorListener => SCALE_FACTOR_LISTENER_INTERFACE,
            Interface::Screenshot => SCREENSHOT_INTERFACE,
            Interface::SerialConsoleFrontend => SERIAL_CONSOLE_FRONTEND_INTERFACE,
            Interface::SerialDevice => SERIAL_DEVICE_INTERFACE,
            Interface::Signal => SIGNAL_INTERFACE,
            Interface::SimpleDispatcher => SIMPLE_DISPATCHER_INTERFACE,
            Interface::SimpleInterrupt => SIMPLE_INTERRUPT_INTERFACE,
            Interface::SimulatorCache => SIMULATOR_CACHE_INTERFACE,
            Interface::SparcV8 => SPARC_V8_INTERFACE,
            Interface::SparcV8EccFaultInjection => SPARC_V8_ECC_FAULT_INJECTION_INTERFACE,
            Interface::Spr => SPR_INTERFACE,
            Interface::Stall => STALL_INTERFACE,
            Interface::Step => STEP_INTERFACE,
            Interface::StepCycleRatio => STEP_CYCLE_RATIO_INTERFACE,
            Interface::StepInfo => STEP_INFO_INTERFACE,
            Interface::SynchronousMode => SYNCHRONOUS_MODE_INTERFACE,
            Interface::Table => TABLE_INTERFACE,
            Interface::TelnetConnection => TELNET_CONNECTION_INTERFACE,
            Interface::TemporalState => TEMPORAL_STATE_INTERFACE,
            Interface::Transaction => TRANSACTION_INTERFACE,
            Interface::TransactionTranslator => TRANSACTION_TRANSLATOR_INTERFACE,
            Interface::Translate => TRANSLATE_INTERFACE,
            Interface::TranslationFlush => TRANSLATION_FLUSH_INTERFACE,
            Interface::Translator => TRANSLATOR_INTERFACE,
            Interface::Uint64State => UINT64_STATE_INTERFACE,
            Interface::Usb => USB_INTERFACE,
            Interface::UsbDevice => USB_DEVICE_INTERFACE,
            Interface::VectoredInterrupt => VECTORED_INTERRUPT_INTERFACE,
            Interface::VectoredInterruptSource => VECTORED_INTERRUPT_SOURCE_INTERFACE,
            Interface::VgaTextInfo => VGA_TEXT_INFO_INTERFACE,
            Interface::VgaTextUpdate => VGA_TEXT_UPDATE_INTERFACE,
            Interface::VgaUpdate => VGA_UPDATE_INTERFACE,
            Interface::VirtualDataBreakpoint => VIRTUAL_DATA_BREAKPOINT_INTERFACE,
            Interface::Vmp => VMP_INTERFACE,
            Interface::VncServer => VNC_SERVER_INTERFACE,
            Interface::X86 => X86_INTERFACE,
            Interface::X86AddressQuery => X86_ADDRESS_QUERY_INTERFACE,
            Interface::X86CacheFlush => X86_CACHE_FLUSH_INTERFACE,
            Interface::X86Cpuid => X86_CPUID_INTERFACE,
            Interface::X86CpuidQuery => X86_CPUID_QUERY_INTERFACE,
            Interface::X86Cstate => X86_CSTATE_INTERFACE,
            Interface::X86CstateNotification => X86_CSTATE_NOTIFICATION_INTERFACE,
            Interface::X86Exception => X86_EXCEPTION_INTERFACE,
            Interface::X86ExceptionQuery => X86_EXCEPTION_QUERY_INTERFACE,
            Interface::X86InstructionQuery => X86_INSTRUCTION_QUERY_INTERFACE,
            Interface::X86MemoryAccess => X86_MEMORY_ACCESS_INTERFACE,
            Interface::X86MemoryOperation => X86_MEMORY_OPERATION_INTERFACE,
            Interface::X86Msr => X86_MSR_INTERFACE,
            Interface::X86PkgCstate => X86_PKG_CSTATE_INTERFACE,
            Interface::X86RegAccess => X86_REG_ACCESS_INTERFACE,
            Interface::X86Smm => X86_SMM_INTERFACE,
            Interface::X86SmmState => X86_SMM_STATE_INTERFACE,
            Interface::X86Tlb => X86_TLB_INTERFACE,
            Interface::X86TlbV2 => X86_TLB_V2_INTERFACE,
            Interface::X86TlbV3 => X86_TLB_V3_INTERFACE,
            Interface::X86VmpControl => X86_VMP_CONTROL_INTERFACE,
            Interface::XedAccess => XED_ACCESS_INTERFACE,
            Interface::XtensaExportState => XTENSA_EXPORT_STATE_INTERFACE,
            Interface::XtensaImportWire => XTENSA_IMPORT_WIRE_INTERFACE,
            Interface::XtensaInputQueue => XTENSA_INPUT_QUEUE_INTERFACE,
            Interface::XtensaLookup => XTENSA_LOOKUP_INTERFACE,
            Interface::XtensaOutputQueue => XTENSA_OUTPUT_QUEUE_INTERFACE,
            Interface::XtensaTieExportState => XTENSA_TIE_EXPORT_STATE_INTERFACE,
            Interface::XtensaTieImportWire => XTENSA_TIE_IMPORT_WIRE_INTERFACE,
            Interface::XtensaTieInputQueue => XTENSA_TIE_INPUT_QUEUE_INTERFACE,
            Interface::XtensaTieLookup => XTENSA_TIE_LOOKUP_INTERFACE,
            Interface::XtensaTieOutputQueue => XTENSA_TIE_OUTPUT_QUEUE_INTERFACE,
            Interface::Other(name) => unsafe {
                from_raw_parts(raw_cstr(name)? as *const u8, name.len() + 1)
            },
        })
    }
}
