
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/rhart/simics-public/simics-6.0.174
RAW_SIMICS_MODEL_BUILDER=/home/rhart/simics-public/simics-6.0.174
RAW_EML_PACKAGE=/home/rhart/simics-public/simics-doc-and-packaging-6.0.53
RAW_DODOC_PKG=/home/rhart/simics-public/simics-6.0.174

RAW_SIMICS_PACKAGE_LIST=/home/rhart/hub/tsffs/.package-list

INCLUDE_PATHS = /home/rhart/simics-public/simics-6.0.174/src/include
CXX_INCLUDE_PATHS = /home/rhart/simics-public/simics-6.0.174/linux64/api
DML_INCLUDE_PATHS = /home/rhart/simics-public/simics-6.0.174/linux64/bin/dml/api
HOST_TYPE = linux64
