#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/rhart/simics-public/simics-6.0.174"
export SIMICS_BASE_PACKAGE
if [ -f "/home/rhart/hub/tsffs/.package-list" ]; then
    exec "/home/rhart/simics-public/simics-6.0.174/bin/simics-eclipse" --package-list "/home/rhart/hub/tsffs/.package-list" --project "/home/rhart/hub/tsffs" "$@"
else
    exec "/home/rhart/simics-public/simics-6.0.174/bin/simics-eclipse" --project "/home/rhart/hub/tsffs" "$@"
fi
