# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "version-tools-fuzz"
description = "Fuzz test cases for version-tools"
edition = "2021"
publish = false
version = "0.0.0"


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.version-tools]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_version_constraint_parse"
path = "fuzz_targets/fuzz_version_constraint_parse.rs"
test = false
doc = false
