//! Build script for the low-level sys bindings crate to the SIMCS API implemented in:
//!
//! - libsimics-common.so
//! - libvtutils.so
//!
//! This build script requires the following environment variables to be set:
//!
//! - `SIMICS_BASE`
//! - `PYTHON3_INCLUDE`
//! - `INCLUDE_PATHS`
//! - `PYTHON3_LDFLAGS`
//! - `LDFLAGS`
//! - `LIBS`
//!
//! For test and development builds (e.g. under rust-analyzer), these values can be manually set
//! in the build environment, e.g. through the workspace's `.vscode/settings.json` file.
//!
//! Given a SIMICS installation directory /home/user/simics/ and a latest SIMICS base
//! version of 6.0.174, the variables would be set like so:
//!
//! - `SIMICS_BASE=/home/user/simics/simics-6.0.174`
//! - `PYTHON3_INCLUDE=-I/home/user/simics/simics-6.0.174/linux64/include/python3.9`
//! - `INCLUDE_PATHS=/home/user/simics/simics-6.0.174/src/include`
//! - `PYTHON3_LDFLAGS=/home/user/simics/simics-6.0.174/linux64/sys/lib/libpython3.so`
//!     - NOTE: This is *not* actually the shared object that needs to be linked against, we must
//!       link against the versioned shared object in the same directory e.g. libpython3.9.so.1.0.
//! - `LDFLAGS=-L/home/user/simics/simics-6.0.174/linux64/bin -z noexecstack -z relro -z now`
//! - `LIBS=-lsimics-common -lvtutils`

use anyhow::{anyhow, bail, ensure, Result};
use bindgen::{
    callbacks::{MacroParsingBehavior, ParseCallbacks},
    AliasVariation, Builder, EnumVariation, FieldVisibilityKind, MacroTypeVariation,
    NonCopyUnionStyle,
};
use scraper::{Html, Selector};
use std::{
    collections::HashSet,
    env::var,
    ffi::OsStr,
    fmt::Write,
    fs::{read, read_dir, write},
    iter::once,
    path::{Path, PathBuf},
};
use walkdir::WalkDir;

// NOTE: The following environment variables are set under the SIMICS package make system
//
// PYTHON: The path to SIMICS's mini-python
// PYTHON3_LDFLAGS: The path to SIMICS's libpython3.so. Starting in 6.0.177, this variable can
// be empty, in which case we use a fallback.
// LIBS: `-lsimics-common -lvtutils`
// CXX_INCLUDE_PATHS: Path to SIMICS_BASE/linux64/api
// PYTHON3: The path to SIMICS's mini-python
// SIMICS_WORKSPACE: The path to the package root
// MOD_MAKEFILE: The makefile being invoked to build the module currently being built
// SIMICS_BASE: The path to the simics base version for the package/project
// DMLC: The path to dml python
// PYTHON3_INCLUDE: -I flag for the path to SIMICS's python3 include directory
// DML_INCLUDE_PATHS: The path to the dml api include directory
// SIMICS_MAJOR_VERSION: The simics major version
// SIMICS_PROJECT: The path to the simics project
// PYTHON_LDFLAGS: The path to SIMICS's libpython3.so
// MODULE_MAKEFILE: The path to the module.mk makefile in simics base
// SRC_BASE: The path to the modules directory for the package
// CCLDFLAGS_DYN: CC/LD flags for dynamic linking
// LDFLAGS: Linker flags to link to libsimics and friends
// SIMICS_PACKAGE_LIST: The path to the .package-list file for this package
// SIMICS_MODEL_BUILDER: The simics used to build models
// PYTHON_INCLUDE: -I flag for the path to SIMICS's python3 include directory
// DMLC_DIR: The path to the simics bin directory containing the dml compiler
// PY2TO3: Path to the py-2to3 tool
// LDFLAGS_PY3: -L flag to include simics base's bin directory
// INCLUDE_PATHS: The path to the SIMICS base include directory

/// Name for the environment variable set by the SIMICS build system to the path to the
/// simics base package. We actually use SIMICS_MODEL_BUILDER here, because we are indeed
/// building a model.
const SIMICS_BASE_ENV: &str = "SIMICS_BASE";
/// Name for the environment variable set by the SIMICS build system to the flag to
/// include e.g.  -I SIMICS_BASE/linux64/include/python3.9/
const PYTHON3_INCLUDE_ENV: &str = "PYTHON3_INCLUDE";
/// Name for the ldflags environment variable, which will point to
/// Name for the environment variable by the SIMICS build system to the path to the
/// simics include directory e.g.  SIMICS_BASE/src/include/
const INCLUDE_PATHS_ENV: &str = "INCLUDE_PATHS";

/// Name for the environment variable set by the SIMICS build system to the libpython3.so library
const PYTHON3_LDFLAGS_ENV: &str = "PYTHON3_LDFLAGS";
/// Name for the LDFLAGS environment variable set by the SIMICS build system containing
/// the link search path for the libsimics library, among other flags. e.g. -LPATH -z noexecstack
const LDFLAGS_ENV: &str = "LDFLAGS";
/// Name for the environment variable containing shared library link flags for simics common and
/// vtutils
const LIBS_ENV: &str = "LIBS";

/// Name for the environment variable set by cargo to the path to the OUT_DIR used for intermediate
/// build results
const OUT_DIR_ENV: &str = "OUT_DIR";
/// The name of the file generated when generating bindings in auto (package-time) mode.
const AUTO_BINDINGS_FILENAME: &str = "bindings-auto.rs";
/// The name of the file generated including the automatic simics version declaration when
/// generating bindings in auto (package-time) mode.
const AUTO_BINDINGS_VERSION_FILENAME: &str = "version-auto.rs";

#[cfg(not(windows))]
/// The name of the binary/library/object subdirectory on linux systems
const HOST_DIRNAME: &str = "linux64";
#[cfg(windows)]
/// The name of the binary/library/object subdirectory on windows systems
const HOST_DIRNAME: &str = "win64";

/// The path in SIMICS_BASE/HOST_TYPE/ of the HTML file containing HAP documentation required
/// for high level codegen of builtin HAPs
const HAP_DOC_PATH: &str = "doc/html/rm-base/rm-haps.html";

// https://github.com/rust-lang/rust-bindgen/issues/687#issuecomment-1312298570
const IGNORE_MACROS: [&str; 20] = [
    "FE_DIVBYZERO",
    "FE_DOWNWARD",
    "FE_INEXACT",
    "FE_INVALID",
    "FE_OVERFLOW",
    "FE_TONEAREST",
    "FE_TOWARDZERO",
    "FE_UNDERFLOW",
    "FE_UPWARD",
    "FP_INFINITE",
    "FP_INT_DOWNWARD",
    "FP_INT_TONEAREST",
    "FP_INT_TONEARESTFROMZERO",
    "FP_INT_TOWARDZERO",
    "FP_INT_UPWARD",
    "FP_NAN",
    "FP_NORMAL",
    "FP_SUBNORMAL",
    "FP_ZERO",
    "IPPORT_RESERVED",
];

const HDR_BLOCKLIST: [&str; 9] = [
    // Most of these are denylisted because they include follower-time.h and it's :/ broken
    "global.h",
    "vtutils.h",
    "libfollower.h",
    "follower-time.h",
    "follower.h",
    "link-endpoint.h",
    "data-structs.h",
    // slave-time.h/slave.h is also broken (it is the old name for follower)
    "slave-time.h",
    "slave.h",
];

#[derive(Debug)]
struct IgnoreMacros(HashSet<String>);

impl ParseCallbacks for IgnoreMacros {
    fn will_parse_macro(&self, name: &str) -> MacroParsingBehavior {
        if self.0.contains(name) {
            MacroParsingBehavior::Ignore
        } else {
            MacroParsingBehavior::Default
        }
    }
}

impl IgnoreMacros {
    fn new() -> Self {
        Self(IGNORE_MACROS.into_iter().map(|s| s.to_string()).collect())
    }
}

fn generate_include_wrapper<P, S>(simics_include_path: P, hap_code: S) -> Result<String>
where
    P: AsRef<Path>,
    S: AsRef<str>,
{
    let simics_include_path = simics_include_path.as_ref().to_path_buf().canonicalize()?;
    let mut include_paths = WalkDir::new(&simics_include_path)
        .into_iter()
        .filter_map(|p| p.ok())
        .filter_map(|p| {
            let simics_include_path = &simics_include_path;
            match p.path().extension() {
                Some(e) => {
                    if e == "h" {
                        match p.path().canonicalize() {
                            Ok(p) => p.strip_prefix(simics_include_path).map_or_else(
                                |e| {
                                    eprintln!(
                                        "cargo:warning=Failed to strip prefix {} from {}: {}",
                                        simics_include_path.display(),
                                        p.display(),
                                        e
                                    );
                                    None::<PathBuf>
                                },
                                |p| Some(p.to_path_buf()),
                            ),
                            Err(e) => {
                                eprintln!(
                                    "cargo:warning=Failed to canonicalize path {}: {}",
                                    p.path().display(),
                                    e
                                );
                                None
                            }
                        }
                    } else {
                        eprintln!(
                            "cargo:warning=Ignoring path {}, no '.h' extension",
                            p.path().display()
                        );
                        None
                    }
                }
                None => {
                    eprintln!(
                        "cargo:warning=Ignoring path {}, no extension",
                        p.path().display()
                    );
                    None
                }
            }
        })
        .collect::<Vec<_>>();

    // We need to move python-header.h to the beginning of the list
    if let Some(python_hdr_pos) = include_paths
        .iter()
        .position(|p| p.file_name() == Some(OsStr::new("python-header.h")))
    {
        include_paths.swap(0, python_hdr_pos);
    }

    HDR_BLOCKLIST.iter().for_each(|le| {
        if let Some(pos) = include_paths
            .iter()
            .position(|p| p.file_name() == Some(OsStr::new(le)))
        {
            include_paths.remove(pos);
        }
    });

    let include_stmts = include_paths
        .iter()
        .map(|p| format!("#include <{}>", p.display()))
        .collect::<Vec<_>>();
    let wrapper = include_stmts.join("\n") + "\n" + hap_code.as_ref();

    println!("{wrapper}");

    Ok(wrapper)
}

/// Get the only subdirectory of a directory, if only one exists. If zero or more than one subdirectories
/// exist, returns an error
fn subdir<P>(dir: P) -> Result<PathBuf>
where
    P: AsRef<Path>,
{
    let subdirs = read_dir(dir)?
        .filter_map(|p| p.ok())
        .map(|p| p.path())
        .filter(|p| p.is_dir())
        .collect::<Vec<_>>();
    ensure!(
        subdirs.len() == 1,
        "Expected exactly 1 sub-directory, found {}",
        subdirs.len()
    );

    subdirs
        .first()
        .cloned()
        .ok_or_else(|| anyhow!("No sub-directories found"))
}

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");

    let base_dir_path = PathBuf::from(
        var(SIMICS_BASE_ENV)
            .map_err(|e| anyhow!("No environment variable {SIMICS_BASE_ENV} found: {e}"))?,
    );

    ensure!(
        base_dir_path.is_dir(),
        "{} is not a directory",
        base_dir_path.display()
    );

    let hap_doc_path = base_dir_path.join(HOST_DIRNAME).join(HAP_DOC_PATH);

    let hap_document =
        Html::parse_document(&String::from_utf8(read(&hap_doc_path).map_err(|e| {
            anyhow!(
                "Error reading document path {} to extract HAP definitions: {e}",
                hap_doc_path.display()
            )
        })?)?);

    let haps_selector = Selector::parse(r#"article"#).unwrap();
    let haps_id_selector = Selector::parse(r#"h2"#).unwrap();
    let section_selector = Selector::parse(r#"section"#).unwrap();
    let hap_code_selector = Selector::parse(r#"pre"#).unwrap();
    let hap_description_selector = Selector::parse(r#"h3"#).unwrap();
    let hap_index_selector = Selector::parse(r#"code"#).unwrap();

    let haps_article = hap_document.select(&haps_selector).next().unwrap();
    let haps_names = haps_article
        .select(&haps_id_selector)
        .filter_map(|h| h.value().id())
        .collect::<Vec<_>>();
    let haps_sections = haps_article.select(&section_selector).collect::<Vec<_>>();
    let haps_code_indices_descriptions = haps_sections
        .iter()
        .map(|s| {
            let code = s
                .select(&hap_code_selector)
                .next()
                .unwrap()
                .inner_html()
                .trim()
                .to_string();
            let maybe_index = s
                .select(&hap_index_selector)
                .next()
                .map(|i| i.inner_html().trim().to_string());
            let maybe_description = s
                .select(&hap_description_selector)
                .last()
                .and_then(|i| i.next_sibling())
                .and_then(|n| n.value().as_text().map(|t| t.trim().to_string()));
            (code, maybe_index, maybe_description)
        })
        .collect::<Vec<_>>();

    let hap_code = haps_names
        .iter()
        .zip(haps_code_indices_descriptions.iter())
        .try_fold(
            String::default(),
            |mut s, (name, (code, maybe_index, maybe_description))| {
                let mut hap_name_name = name.to_ascii_uppercase();
                hap_name_name += "_HAP_NAME";
                let mut hap_callback_name = name.to_ascii_lowercase();
                hap_callback_name += "_hap_callback";
                let code = code
                    .replace("(*)", &format!("(*{})", hap_callback_name))
                    .replace(['/', '-'], "_");
                let comment = format!(
                    "/**\n * Index: {}\n * Description: {}\n */",
                    maybe_index
                        .as_ref()
                        .unwrap_or(&"Indices not supported".to_string()),
                    maybe_description
                        .as_ref()
                        .unwrap_or(&"No description".to_string())
                );

                write!(
                    &mut s,
                    "#define {} \"{}\"\n{}\ntypedef {}\n",
                    hap_name_name, name, comment, code
                )
                .and_then(|_| Ok(s))
            },
        )?;

    let simics_base_version = base_dir_path
                .file_name()
                .ok_or_else(|| anyhow!("No file name found in SIMICS base path"))?
                .to_str()
                .ok_or_else(|| anyhow!("Could not convert file name to string"))?
                .split('-')
                .last()
                .ok_or_else(|| anyhow!("Could not split to obtain version: SIMICS base directory may not be in the format simics-X.X.XXX"))?
                .to_string();

    let simics_base_version_const_declaration = format!(
        r#"pub const SIMICS_VERSION: &str = "{}";"#,
        simics_base_version
    );

    let out_dir_path = PathBuf::from(
        var(OUT_DIR_ENV)
            .map_err(|e| anyhow!("No environment variable {OUT_DIR_ENV} found: {e}"))?,
    );

    let bindings_file_path = out_dir_path.join(AUTO_BINDINGS_FILENAME);
    let version_file_path = out_dir_path.join(AUTO_BINDINGS_VERSION_FILENAME);

    write(version_file_path, simics_base_version_const_declaration)?;

    let include_paths_env = var(INCLUDE_PATHS_ENV).or_else(|e| {
            println!("cargo:warning=No environment variable {INCLUDE_PATHS_ENV} set. Using default include paths: {e}");
            base_dir_path
                .join("src")
                .join("include")
                .to_str()
                .map(|s| s.to_string())
                .ok_or_else(|| anyhow!("Could not convert path to string"))
        })?;

    let include_paths = PathBuf::from(&include_paths_env);

    let wrapper_contents = generate_include_wrapper(include_paths, hap_code)?;

    let bindings =
            Builder::default()
                .clang_arg(var(PYTHON3_INCLUDE_ENV).or_else(|e| {
                    println!("cargo:warning=No environment variable {PYTHON3_INCLUDE_ENV} set. Using default include paths: {e}");
                    subdir(base_dir_path
                        .join(HOST_DIRNAME)
                        .join("include"))
                        .and_then(|p| {
                            p.to_str()
                            .map(|s| format!("-I{}", s))
                            .ok_or_else(|| anyhow!("Could not convert path to string"))
                        })
                })?)
                .clang_arg(format!("-I{}", include_paths_env,))
                .clang_arg("-fretain-comments-from-system-headers")
                .clang_arg("-fparse-all-comments")
                // We don't care at all what warnings simics has if they aren't errors :)
                .clang_arg("-Wno-everything")
                .default_visibility(FieldVisibilityKind::Public)
                .default_alias_style(AliasVariation::TypeAlias)
                .default_enum_style(EnumVariation::Rust {
                    non_exhaustive: false,
                })
                .default_macro_constant_type(MacroTypeVariation::Unsigned)
                .default_non_copy_union_style(NonCopyUnionStyle::BindgenWrapper)
                .derive_default(true)
                .derive_hash(true)
                .derive_partialord(true)
                .derive_ord(true)
                .derive_eq(true)
                .derive_partialeq(true)
                .generate_comments(true)
                .header_contents("wrapper.h", &wrapper_contents)
                // NOTE: These callbacks are required to emit `cargo:rerun-if-changed`
                // statements, so we do not need to use them in this script. If you want to
                // repurpose this script to use in a `build.rs`, you should re-enable this
                // line:
                // .parse_callbacks(Box::new(CargoCallbacks))
                .parse_callbacks(Box::new(IgnoreMacros::new()))
                // These functions are extraneous and only emitted due to the include wrappers
                // eventually including system headers which provide a huge number of unused
                // symbols.
                .blocklist_items(FUNCS_BLOCKLIST)
                .blocklist_items(CONSTS_BLOCKLIST)
                // Blocklisted because packed and align reprs differ
                .blocklist_type("__mingw_ldbl_type_t")
                .bitfield_enum("event_class_flag_t")
                .bitfield_enum("micro_checkpoint_flags_t")
                .bitfield_enum("access_t")
                .bitfield_enum("breakpoint_flag")
                .bitfield_enum("save_flags_t")
                // Blocklisted because not used and adds confusion
                .generate()?;

    bindings.write_to_file(bindings_file_path)?;

    if cfg!(feature = "link") {
        let base_dir_path = PathBuf::from(
            var(SIMICS_BASE_ENV)
                .map_err(|e| anyhow!("No environment variable {SIMICS_BASE_ENV} found: {e}"))?,
        );

        ensure!(
            base_dir_path.is_dir(),
            "{} is not a directory",
            base_dir_path.display()
        );

        let libpython_path =
            PathBuf::from(var(PYTHON3_LDFLAGS_ENV).map_err(|e| {
                anyhow!("No environment variable {PYTHON3_LDFLAGS_ENV} found: {e}")
            }).and_then(|v| if v.is_empty() { bail!("Environment variable {PYTHON3_LDFLAGS_ENV} is empty") } else { Ok(v) }).or_else(|e| {
                println!("cargo:warning=No environment variable {INCLUDE_PATHS_ENV} set. Using default include paths: {e}");
                base_dir_path
                    .join(HOST_DIRNAME)
                    .join("sys")
                    .join("lib")
                    .join("libpython3.so")
                    .to_str()
                    .map(|s| s.to_string())
                    .ok_or_else(|| anyhow!("Could not convert path to string"))
            })?);

        let libpython_dir = libpython_path
            .parent()
            .ok_or_else(|| anyhow!("libpython path {} has no parent", libpython_path.display()))?
            .to_path_buf();

        let link_search_paths = var(LDFLAGS_ENV)
            .or_else(|e| {
                println!("cargo:warning=No environment variable {LDFLAGS_ENV} set. Using default include paths: {e}");
                base_dir_path
                    .join(HOST_DIRNAME)
                    .join("bin")
                    .to_str()
                    .map(|s| format!("-L{}", s))
                    .ok_or_else(|| anyhow!("Could not convert path to string"))
            })?
            .split_whitespace()
            .filter_map(|s| s.starts_with("-L").then_some(s.replace("-L", "")))
            .map(PathBuf::from)
            .chain(once(libpython_dir))
            .collect::<Vec<_>>();

        #[cfg(not(windows))]
        let libs = var(LIBS_ENV)
            .unwrap_or_else(|e| {
                println!("cargo:warning=No environment variable {LIBS_ENV} set. Using default include paths: {e}");
                "-lsimics-common -lvtutils".to_string()
            })
            .split_whitespace()
            .filter_map(|s| s.starts_with("-l").then_some(s.replace("-l", "")))
            .collect::<Vec<_>>();

        #[cfg(windows)]
        let libs = "-lsimics-common -lvtutils"
            .split_whitespace()
            .filter_map(|s| s.starts_with("-l").then_some(s.replace("-l", "")))
            .collect::<Vec<_>>();

        link_search_paths.iter().for_each(|p| {
            // NOTE: These are removed by cargo, which is why we use absolute paths.
            // We emit them just for posterity
            println!("cargo:rustc-link-search=native={}", p.display());
            // NOTE: This is needed for the recursive linking step against libpython from
            // libsimics-common.so
            println!("cargo:rustc-link-arg=-Wl,-rpath-link,{}", p.display());
            // NOTE: This is needed so we can locate the shared libraries at runtime, because
            // unlike the `simics` script in each project, we don't get to write an absolute
            // path
            // println!("cargo-rustc-link-arg=-Wl,-rpath,{}", p.display());
            // println!("cargo-rustc-cdylib-link-arg=-Wl,-rpath,{}", p.display());
            // println!("cargo-rustc-link-arg=-Wl,-rpath={}", p.display());
            // println!("cargo-rustc-cdylib-link-arg=-Wl,-rpath={}", p.display());
        });

        libs.iter()
            .for_each(|l| println!("cargo:rustc-link-lib=dylib={}", l));

        let library_search_paths = link_search_paths
            .iter()
            .map(|p| {
                p.to_str()
                    .ok_or_else(|| anyhow!("Could not convert path {} to string", p.display()))
            })
            .collect::<Result<Vec<_>>>()?
            .join(":");

        // NOTE: This enables running binaries linked with this one when running with `cargo run`
        println!("cargo:rustc-env=LD_LIBRARY_PATH={}", library_search_paths);

        // NOTE:
        // EVEN with all of the above, a binary built using `cargo build` will not be able to find
        // libsimics-common.so. Instead, when we build a binary that transitively depends on this
        // -sys crate, we compile it with `cargo rustc`, passing the `-rpath` link argument like
        // so. Note `--disable-new-dtags`, otherwise `libsimics-common.so` cannot find
        // `libpython3.9.so.1.0` because it will be missing the recursive rpath lookup.

        // SIMICS_BASE=/home/rhart/simics-public/simics-6.0.174
        // PYTHON3_INCLUDE=-I/home/rhart/simics-public/simics-6.0.174/linux64/include/python3.9
        // INCLUDE_PATHS=/home/rhart/simics-public/simics-6.0.174/src/include
        // PYTHON3_LDFLAGS=/home/rhart/simics-public/simics-6.0.174/linux64/sys/lib/libpython3.so
        // LDFLAGS="-L/home/rhart/simics-public/simics-6.0.174/linux64/bin -z
        // noexecstack -z relro -z now" LIBS="-lsimics-common -lvtutils" cargo rustc
        // --features=auto,link --example simple-simics -- -C
        // link-args="-Wl,--disable-new-dtags
        // -Wl,-rpath,/home/rhart/simics-public/simics-6.0.174/linux64/bin;/home/rhart/simics-public/simics-6.0.174/linux64/sys/lib/"

        // This command (the environment variables can be left out) can be auto-generated in the
        // SIMICS makefile build system.
    }

    Ok(())
}

trait WithBlocklists {
    fn blocklist_functions(self, blocklist: &[&str]) -> Self;
    fn blocklist_items(self, blocklist: &[&str]) -> Self;
    fn blocklist_types(self, blocklist: &[&str]) -> Self;
}

impl WithBlocklists for Builder {
    fn blocklist_functions(self, blocklist: &[&str]) -> Self {
        blocklist.iter().fold(self, |b, f| b.blocklist_function(f))
    }

    fn blocklist_items(self, blocklist: &[&str]) -> Self {
        blocklist.iter().fold(self, |b, f| b.blocklist_item(f))
    }

    fn blocklist_types(self, blocklist: &[&str]) -> Self {
        blocklist.iter().fold(self, |b, f| b.blocklist_type(f))
    }
}

/// Generated with something like:
///
/// rg -Nor '$1' "pub const ([^:]+)[^=]*\s*(.*);" target/debug/build/simics-api-sys-ae6e3cb0e0e0db62/out/bindings-auto.rs | sort | uniq > /tmp/nokeep.txt
/// rg -Nor '$1' "pub const ([^:]+)[^=]*\s*(.*);" target/debug/build/simics-api-sys-ae6e3cb0e0e0db62/out/bindings-auto.rs | xargs -i bash -c 'if rg -g "!host-info.h" -g "!module-host-config.h" -g "!base-types.h" -g "!python-header.h" " {}" /home/rhart/simics/simics-6.0.169/src/include | rg -vq "undef|ifdef";then echo "{}"; fi' | sort | uniq > /tmp/keep.txt
/// comm -23 /tmp/nokeep.txt /tmp/keep.txt | rg -v "bindgen|SIM|VT|vt|sim|mm|HAP_NAME" | xclip -selection copy
const CONSTS_BLOCKLIST: &[&str; 1782] = &[
    "ACCESSPERMS",
    "AF_ALG",
    "AF_APPLETALK",
    "AF_ASH",
    "AF_ATMPVC",
    "AF_ATMSVC",
    "AF_AX25",
    "AF_BLUETOOTH",
    "AF_BRIDGE",
    "AF_CAIF",
    "AF_CAN",
    "AF_DECnet",
    "AF_ECONET",
    "AF_FILE",
    "AF_IB",
    "AF_IEEE802154",
    "AF_INET",
    "AF_INET6",
    "AF_IPX",
    "AF_IRDA",
    "AF_ISDN",
    "AF_IUCV",
    "AF_KCM",
    "AF_KEY",
    "AF_LLC",
    "AF_LOCAL",
    "AF_MAX",
    "AF_MCTP",
    "AF_MPLS",
    "AF_NETBEUI",
    "AF_NETLINK",
    "AF_NETROM",
    "AF_NFC",
    "AF_PACKET",
    "AF_PHONET",
    "AF_PPPOX",
    "AF_QIPCRTR",
    "AF_RDS",
    "AF_ROSE",
    "AF_ROUTE",
    "AF_RXRPC",
    "AF_SECURITY",
    "AF_SMC",
    "AF_SNA",
    "AF_TIPC",
    "AF_UNIX",
    "AF_UNSPEC",
    "AF_VSOCK",
    "AF_WANPIPE",
    "AF_X25",
    "AF_XDP",
    "AIO_PRIO_DELTA_MAX",
    "_ALLOCA_H",
    "ALLPERMS",
    "_ALL_SOURCE",
    "ARG_MAX",
    "ARPD_FLUSH",
    "ARPD_LOOKUP",
    "ARPD_UPDATE",
    "ARPHRD_ADAPT",
    "ARPHRD_APPLETLK",
    "ARPHRD_ARCNET",
    "ARPHRD_ASH",
    "ARPHRD_ATM",
    "ARPHRD_AX25",
    "ARPHRD_BIF",
    "ARPHRD_CAN",
    "ARPHRD_CHAOS",
    "ARPHRD_CISCO",
    "ARPHRD_CSLIP",
    "ARPHRD_CSLIP6",
    "ARPHRD_DDCMP",
    "ARPHRD_DLCI",
    "ARPHRD_ECONET",
    "ARPHRD_EETHER",
    "ARPHRD_ETHER",
    "ARPHRD_EUI64",
    "ARPHRD_FCAL",
    "ARPHRD_FCFABRIC",
    "ARPHRD_FCPL",
    "ARPHRD_FCPP",
    "ARPHRD_FDDI",
    "ARPHRD_FRAD",
    "ARPHRD_HDLC",
    "ARPHRD_HIPPI",
    "ARPHRD_HWX25",
    "ARPHRD_IEEE1394",
    "ARPHRD_IEEE802",
    "ARPHRD_IEEE80211",
    "ARPHRD_IEEE80211_PRISM",
    "ARPHRD_IEEE80211_RADIOTAP",
    "ARPHRD_IEEE802154",
    "ARPHRD_IEEE802154_PHY",
    "ARPHRD_IEEE802_TR",
    "ARPHRD_INFINIBAND",
    "ARPHRD_IPDDP",
    "ARPHRD_IPGRE",
    "ARPHRD_IRDA",
    "ARPHRD_LAPB",
    "ARPHRD_LOCALTLK",
    "ARPHRD_LOOPBACK",
    "ARPHRD_MCTP",
    "ARPHRD_METRICOM",
    "ARPHRD_NETROM",
    "ARPHRD_NONE",
    "ARPHRD_PIMREG",
    "ARPHRD_PPP",
    "ARPHRD_PRONET",
    "ARPHRD_RAWHDLC",
    "ARPHRD_RAWIP",
    "ARPHRD_ROSE",
    "ARPHRD_RSRVD",
    "ARPHRD_SIT",
    "ARPHRD_SKIP",
    "ARPHRD_SLIP",
    "ARPHRD_SLIP6",
    "ARPHRD_TUNNEL",
    "ARPHRD_TUNNEL6",
    "ARPHRD_VOID",
    "ARPHRD_X25",
    "ARPOP_InREPLY",
    "ARPOP_InREQUEST",
    "ARPOP_NAK",
    "ARPOP_REPLY",
    "ARPOP_REQUEST",
    "ARPOP_RREPLY",
    "ARPOP_RREQUEST",
    "_ASSERT_H",
    "ATF_COM",
    "ATF_DONTPUB",
    "_ATFILE_SOURCE",
    "ATF_MAGIC",
    "ATF_NETMASK",
    "ATF_PERM",
    "ATF_PUBL",
    "ATF_USETRAILERS",
    "BC_BASE_MAX",
    "BC_DIM_MAX",
    "BC_SCALE_MAX",
    "BC_STRING_MAX",
    "__BIG_ENDIAN",
    "_BITS_BYTESWAP_H",
    "_BITS_CPU_SET_H",
    "_BITS_ENDIAN_H",
    "_BITS_ENDIANNESS_H",
    "_BITS_ERRNO_H",
    "_BITS_LIBM_SIMD_DECL_STUBS_H",
    "__BITS_PER_LONG",
    "_BITS_POSIX1_LIM_H",
    "_BITS_POSIX2_LIM_H",
    "_BITS_POSIX_OPT_H",
    "_BITS_PTHREADTYPES_ARCH_H",
    "_BITS_PTHREADTYPES_COMMON_H",
    "_BITS_SCHED_H",
    "_BITS_SETJMP_H",
    "_BITS_SOCKADDR_H",
    "_BITS_STAT_H",
    "_BITS_STDINT_INTN_H",
    "_BITS_STDINT_UINTN_H",
    "_BITS_STDIO_LIM_H",
    "_BITS_STRUCT_STAT_H",
    "_BITS_TIME64_H",
    "_BITS_TIME_H",
    "_BITS_TYPES_H",
    "_BITS_TYPESIZES_H",
    "_BITS_TYPES___LOCALE_T_H",
    "_BITS_TYPES_LOCALE_T_H",
    "_BITS_TYPES_STRUCT_SCHED_PARAM",
    "_BITS_UINTN_IDENTITY_H",
    "_BITS_WCHAR_H",
    "__BIT_TYPES_DEFINED__",
    "__bool_true_false_are_defined",
    "__BSD_VISIBLE",
    "BUFSIZ",
    "__BYTE_ORDER",
    "BYTE_ORDER",
    "CHARCLASS_NAME_MAX",
    "CLOCK_BOOTTIME",
    "CLOCK_BOOTTIME_ALARM",
    "__clockid_t_defined",
    "CLOCK_MONOTONIC",
    "CLOCK_MONOTONIC_COARSE",
    "CLOCK_MONOTONIC_RAW",
    "CLOCK_PROCESS_CPUTIME_ID",
    "CLOCK_REALTIME",
    "CLOCK_REALTIME_ALARM",
    "CLOCK_REALTIME_COARSE",
    "CLOCK_TAI",
    "__clock_t_defined",
    "CLOCK_THREAD_CPUTIME_ID",
    "CO_ASYNC_GENERATOR",
    "CO_CELL_NOT_AN_ARG",
    "CO_COROUTINE",
    "CO_FUTURE_ABSOLUTE_IMPORT",
    "CO_FUTURE_ANNOTATIONS",
    "CO_FUTURE_BARRY_AS_BDFL",
    "CO_FUTURE_DIVISION",
    "CO_FUTURE_GENERATOR_STOP",
    "CO_FUTURE_PRINT_FUNCTION",
    "CO_FUTURE_UNICODE_LITERALS",
    "CO_FUTURE_WITH_STATEMENT",
    "CO_GENERATOR",
    "CO_ITERABLE_COROUTINE",
    "COLL_WEIGHTS_MAX",
    "CO_MAXBLOCKS",
    "CO_NESTED",
    "CO_NEWLOCALS",
    "CO_NOFREE",
    "__cookie_io_functions_t_defined",
    "CO_OPTIMIZED",
    "CO_VARARGS",
    "CO_VARKEYWORDS",
    "__CPU_SETSIZE",
    "_CS_GNU_LIBC_VERSION",
    "_CS_GNU_LIBPTHREAD_VERSION",
    "_CS_LFS64_CFLAGS",
    "_CS_LFS64_LDFLAGS",
    "_CS_LFS64_LIBS",
    "_CS_LFS64_LINTFLAGS",
    "_CS_LFS_CFLAGS",
    "_CS_LFS_LDFLAGS",
    "_CS_LFS_LIBS",
    "_CS_LFS_LINTFLAGS",
    "_CS_PATH",
    "_CS_POSIX_V6_LP64_OFF64_LIBS",
    "_CS_POSIX_V7_LP64_OFF64_LIBS",
    "_CS_V5_WIDTH_RESTRICTED_ENVS",
    "_CS_V6_ENV",
    "_CS_V6_WIDTH_RESTRICTED_ENVS",
    "_CS_V7_ENV",
    "_CS_V7_WIDTH_RESTRICTED_ENVS",
    "_CS_XBS5_ILP32_OFF32_CFLAGS",
    "_CS_XBS5_ILP32_OFF32_LDFLAGS",
    "_CS_XBS5_ILP32_OFF32_LIBS",
    "_CS_XBS5_ILP32_OFFBIG_CFLAGS",
    "_CS_XBS5_ILP32_OFFBIG_LIBS",
    "_CS_XBS5_LP64_OFF64_CFLAGS",
    "_CS_XBS5_LP64_OFF64_LDFLAGS",
    "_CS_XBS5_LP64_OFF64_LIBS",
    "_CS_XBS5_LPBIG_OFFBIG_CFLAGS",
    "_CS_XBS5_LPBIG_OFFBIG_LIBS",
    "_CTYPE_H",
    "_DARWIN_C_SOURCE",
    "_DEFAULT_SOURCE",
    "DEFFILEMODE",
    "DELAYTIMER_MAX",
    "DIR_SEP",
    "DIR_SEP_CHAR",
    "_DLFCN_H",
    "DOUBLE_IS_LITTLE_ENDIAN_IEEE754",
    "E2BIG",
    "EACCES",
    "EADDRINUSE",
    "EADDRNOTAVAIL",
    "EADV",
    "EAFNOSUPPORT",
    "EAGAIN",
    "EALREADY",
    "EBADE",
    "EBADF",
    "EBADFD",
    "EBADMSG",
    "EBADR",
    "EBADRQC",
    "EBADSLT",
    "EBFONT",
    "EBUSY",
    "ECANCELED",
    "ECHILD",
    "ECHRNG",
    "ECOMM",
    "ECONNABORTED",
    "ECONNREFUSED",
    "ECONNRESET",
    "EDEADLK",
    "EDEADLOCK",
    "EDESTADDRREQ",
    "EDOM",
    "EDOTDOT",
    "EDQUOT",
    "EEXIST",
    "EFAULT",
    "EFBIG",
    "EHOSTDOWN",
    "EHOSTUNREACH",
    "EHWPOISON",
    "EIDRM",
    "EILSEQ",
    "EINPROGRESS",
    "EINTR",
    "EINVAL",
    "EIO",
    "EISCONN",
    "EISDIR",
    "EISNAM",
    "EKEYEXPIRED",
    "EKEYREJECTED",
    "EKEYREVOKED",
    "EL2HLT",
    "EL2NSYNC",
    "EL3HLT",
    "EL3RST",
    "ELIBACC",
    "ELIBBAD",
    "ELIBEXEC",
    "ELIBMAX",
    "ELIBSCN",
    "ELNRNG",
    "ELOOP",
    "EMEDIUMTYPE",
    "EMFILE",
    "EMLINK",
    "EMSGSIZE",
    "EMULTIHOP",
    "ENABLE_IPV6",
    "ENAMETOOLONG",
    "ENAVAIL",
    "_ENDIAN_H",
    "ENETDOWN",
    "ENETRESET",
    "ENETUNREACH",
    "ENFILE",
    "ENOANO",
    "ENOBUFS",
    "ENOCSI",
    "ENODATA",
    "ENODEV",
    "ENOENT",
    "ENOEXEC",
    "ENOKEY",
    "ENOLCK",
    "ENOLINK",
    "ENOMEDIUM",
    "ENOMEM",
    "ENOMSG",
    "ENONET",
    "ENOPKG",
    "ENOPROTOOPT",
    "ENOSPC",
    "ENOSR",
    "ENOSTR",
    "ENOSYS",
    "ENOTBLK",
    "ENOTCONN",
    "ENOTDIR",
    "ENOTEMPTY",
    "ENOTNAM",
    "ENOTRECOVERABLE",
    "ENOTSOCK",
    "ENOTSUP",
    "ENOTTY",
    "ENOTUNIQ",
    "ENXIO",
    "EOF",
    "EOPNOTSUPP",
    "EOVERFLOW",
    "EOWNERDEAD",
    "EPERM",
    "EPFNOSUPPORT",
    "EPIPE",
    "EPROTO",
    "EPROTONOSUPPORT",
    "EPROTOTYPE",
    "ERANGE",
    "EREMCHG",
    "EREMOTE",
    "EREMOTEIO",
    "ERESTART",
    "ERFKILL",
    "EROFS",
    "_ERRNO_H",
    "ESHUTDOWN",
    "ESOCKTNOSUPPORT",
    "ESPIPE",
    "ESRCH",
    "ESRMNT",
    "ESTALE",
    "ESTRPIPE",
    "ETH_DATA_LEN",
    "ETHER_HDR_LEN",
    "ETHERMIN",
    "ETHERMTU",
    "ETHERTYPE_AARP",
    "ETHERTYPE_AT",
    "ETHERTYPE_IPX",
    "ETHER_TYPE_LEN",
    "ETHERTYPE_LOOPBACK",
    "ETHERTYPE_NTRAILER",
    "ETHERTYPE_SPRITE",
    "ETHERTYPE_TRAIL",
    "ETHERTYPE_VLAN",
    "ETH_FCS_LEN",
    "ETH_FRAME_LEN",
    "ETH_HLEN",
    "ETH_MAX_MTU",
    "ETH_MIN_MTU",
    "ETH_P_1588",
    "ETH_P_8021AD",
    "ETH_P_8021AH",
    "ETH_P_8021Q",
    "ETH_P_802_2",
    "ETH_P_80221",
    "ETH_P_802_3",
    "ETH_P_802_3_MIN",
    "ETH_P_802_EX1",
    "ETH_P_AARP",
    "ETH_P_AF_IUCV",
    "ETH_P_ALL",
    "ETH_P_AOE",
    "ETH_P_ARCNET",
    "ETH_P_ARP",
    "ETH_P_ATALK",
    "ETH_P_ATMFATE",
    "ETH_P_ATMMPOA",
    "ETH_P_AX25",
    "ETH_P_BATMAN",
    "ETH_P_BPQ",
    "ETH_P_CAIF",
    "ETH_P_CAN",
    "ETH_P_CANFD",
    "ETH_P_CANXL",
    "ETH_P_CFM",
    "ETH_P_CONTROL",
    "ETH_P_CUST",
    "ETH_P_DDCMP",
    "ETH_P_DEC",
    "ETH_P_DIAG",
    "ETH_P_DNA_DL",
    "ETH_P_DNA_RC",
    "ETH_P_DNA_RT",
    "ETH_P_DSA",
    "ETH_P_DSA_8021Q",
    "ETH_P_DSA_A5PSW",
    "ETH_P_ECONET",
    "ETH_P_EDSA",
    "ETH_P_ERSPAN",
    "ETH_P_ERSPAN2",
    "ETH_P_ETHERCAT",
    "ETH_P_FCOE",
    "ETH_P_FIP",
    "ETH_P_HDLC",
    "ETH_P_HSR",
    "ETH_P_IBOE",
    "ETH_P_IEEE802154",
    "ETH_P_IEEEPUP",
    "ETH_P_IEEEPUPAT",
    "ETH_P_IFE",
    "ETH_P_IP",
    "ETH_P_IPV6",
    "ETH_P_IPX",
    "ETH_P_IRDA",
    "ETH_P_LAT",
    "ETH_P_LINK_CTL",
    "ETH_P_LLDP",
    "ETH_P_LOCALTALK",
    "ETH_P_LOOP",
    "ETH_P_LOOPBACK",
    "ETH_P_MACSEC",
    "ETH_P_MAP",
    "ETH_P_MCTP",
    "ETH_P_MOBITEX",
    "ETH_P_MPLS_MC",
    "ETH_P_MPLS_UC",
    "ETH_P_MRP",
    "ETH_P_MVRP",
    "ETH_P_NCSI",
    "ETH_P_NSH",
    "ETH_P_PAE",
    "ETH_P_PAUSE",
    "ETH_P_PHONET",
    "ETH_P_PPP_DISC",
    "ETH_P_PPP_MP",
    "ETH_P_PPP_SES",
    "ETH_P_PPPTALK",
    "ETH_P_PREAUTH",
    "ETH_P_PROFINET",
    "ETH_P_PRP",
    "ETH_P_PUP",
    "ETH_P_PUPAT",
    "ETH_P_QINQ1",
    "ETH_P_QINQ2",
    "ETH_P_QINQ3",
    "ETH_P_RARP",
    "ETH_P_REALTEK",
    "ETH_P_SCA",
    "ETH_P_SLOW",
    "ETH_P_SNAP",
    "ETH_P_TDLS",
    "ETH_P_TEB",
    "ETH_P_TIPC",
    "ETH_P_TR_802_2",
    "ETH_P_TRAILER",
    "ETH_P_TSN",
    "ETH_P_WAN_PPP",
    "ETH_P_WCCP",
    "ETH_P_X25",
    "ETH_P_XDSA",
    "ETH_TLEN",
    "ETH_ZLEN",
    "ETIME",
    "ETIMEDOUT",
    "ETOOMANYREFS",
    "ETXTBSY",
    "EUCLEAN",
    "EUNATCH",
    "EUSERS",
    "EWOULDBLOCK",
    "EXDEV",
    "EXFULL",
    "EXIT_FAILURE",
    "EXIT_SUCCESS",
    "EXPR_NEST_MAX",
    "__EXTENSIONS__",
    "false_",
    "F_ALT",
    "F_BLANK",
    "__FD_SETSIZE",
    "FD_SETSIZE",
    "_FEATURES_H",
    "____FILE_defined",
    "__FILE_defined",
    "FILENAME_MAX",
    "_FILE_OFFSET_BITS",
    "FIOGETOWN",
    "FIOSETOWN",
    "F_LJUST",
    "__FLOAT_WORD_ORDER",
    "F_LOCK",
    "F_OK",
    "FOPEN_MAX",
    "FP_ILOGB0",
    "FP_ILOGBNAN",
    "FP_INFINITE",
    "__FP_LOGB0_IS_MIN",
    "__FP_LOGBNAN_IS_MIN",
    "FP_NAN",
    "FP_NORMAL",
    "_____fpos64_t_defined",
    "_____fpos_t_defined",
    "FP_SUBNORMAL",
    "FP_ZERO",
    "F_SIGN",
    "F_TEST",
    "F_TLOCK",
    "F_ULOCK",
    "FUTURE_ABSOLUTE_IMPORT",
    "FUTURE_ANNOTATIONS",
    "FUTURE_BARRY_AS_BDFL",
    "FUTURE_DIVISION",
    "FUTURE_GENERATORS",
    "FUTURE_GENERATOR_STOP",
    "FUTURE_NESTED_SCOPES",
    "FUTURE_PRINT_FUNCTION",
    "FUTURE_UNICODE_LITERALS",
    "FUTURE_WITH_STATEMENT",
    "FVC_ASCII",
    "FVC_MASK",
    "FVC_NONE",
    "FVC_REPR",
    "FVC_STR",
    "FVS_HAVE_SPEC",
    "FVS_MASK",
    "F_ZERO",
    "_GETOPT_CORE_H",
    "_GETOPT_POSIX_H",
    "__GLIBC__",
    "__glibc_c99_flexarr_available",
    "__GLIBC_MINOR__",
    "__GLIBC_USE_C2X_STRTOL",
    "__GLIBC_USE_DEPRECATED_GETS",
    "__GLIBC_USE_DEPRECATED_SCANF",
    "__GLIBC_USE_IEC_60559_BFP_EXT",
    "__GLIBC_USE_IEC_60559_BFP_EXT_C2X",
    "__GLIBC_USE_IEC_60559_EXT",
    "__GLIBC_USE_IEC_60559_FUNCS_EXT",
    "__GLIBC_USE_IEC_60559_FUNCS_EXT_C2X",
    "__GLIBC_USE_IEC_60559_TYPES_EXT",
    "__GLIBC_USE_ISOC2X",
    "__GLIBC_USE_LIB_EXT2",
    "__GNU_LIBRARY__",
    "_GNU_SOURCE",
    "____gwchar_t_defined",
    "*HAVE_*",
    "HOST_CACHE_LINE_SIZE",
    "HOST_NAME_MAX",
    "IFF_ALLMULTI",
    "IFF_AUTOMEDIA",
    "IFF_BROADCAST",
    "IFF_DEBUG",
    "IFF_DYNAMIC",
    "IFF_LOOPBACK",
    "IFF_MASTER",
    "IFF_MULTICAST",
    "IFF_NOARP",
    "IFF_NOTRAILERS",
    "IFF_POINTOPOINT",
    "IFF_PORTSEL",
    "IFF_PROMISC",
    "IFF_RUNNING",
    "IFF_SLAVE",
    "IFF_UP",
    "IFHWADDRLEN",
    "IF_NAMESIZE",
    "IFNAMSIZ",
    "__ILP32_OFF32_CFLAGS",
    "__ILP32_OFF32_LDFLAGS",
    "__ILP32_OFFBIG_CFLAGS",
    "__ILP32_OFFBIG_LDFLAGS",
    "__INO_T_MATCHES_INO64_T",
    "INT16_MAX",
    "INT16_MIN",
    "INT32_MAX",
    "INT32_MIN",
    "INT8_MAX",
    "INT8_MIN",
    "INT_FAST16_MAX",
    "INT_FAST16_MIN",
    "INT_FAST32_MAX",
    "INT_FAST32_MIN",
    "INT_FAST8_MAX",
    "INT_FAST8_MIN",
    "INT_LEAST16_MAX",
    "INT_LEAST16_MIN",
    "INT_LEAST32_MAX",
    "INT_LEAST32_MIN",
    "INT_LEAST8_MAX",
    "INT_LEAST8_MIN",
    "INTPTR_MAX",
    "INTPTR_MIN",
    "_INTTYPES_H",
    "_IO_EOF_SEEN",
    "_IO_ERR_SEEN",
    "_IOFBF",
    "_IOLBF",
    "_IONBF",
    "_IO_USER_LOCK",
    "__iovec_defined",
    "_ISalnum",
    "_ISalpha",
    "_ISblank",
    "_IScntrl",
    "_ISdigit",
    "_ISgraph",
    "_ISlower",
    "_ISprint",
    "_ISpunct",
    "_ISspace",
    "_ISupper",
    "_ISxdigit",
    "__itimerspec_defined",
    "__jmp_buf_tag_defined",
    "__KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64",
    "_LARGEFILE64_SOURCE",
    "_LARGEFILE_SOURCE",
    "L_ctermid",
    "__ldiv_t_defined",
    "__LDOUBLE_REDIRECTS_TO_FLOAT128_ABI",
    "_LFS64_ASYNCHRONOUS_IO",
    "_LFS64_LARGEFILE",
    "_LFS64_STDIO",
    "_LFS_ASYNCHRONOUS_IO",
    "_LFS_LARGEFILE",
    "_LIBC_LIMITS_H_",
    "L_INCR",
    "LINE_MAX",
    "LINK_MAX",
    "__LITTLE_ENDIAN",
    "LITTLE_ENDIAN",
    "__lldiv_t_defined",
    "LOGIN_NAME_MAX",
    "LONG_BIT",
    "__LP64_OFF64_CFLAGS",
    "__LP64_OFF64_LDFLAGS",
    "L_SET",
    "L_tmpnam",
    "L_XTND",
    "M_1_PI",
    "M_2_PI",
    "M_2_SQRTPI",
    "__MATH_DECLARE_LDOUBLE",
    "__MATH_DECLARING_DOUBLE",
    "__MATH_DECLARING_FLOATN",
    "MATH_ERREXCEPT",
    "math_errhandling",
    "MATH_ERRNO",
    "_MATH_H",
    "MAX_ADDR_LEN",
    "MAX_CANON",
    "MAX_CO_EXTRA_USERS",
    "MAX_INPUT",
    "MB_LEN_MAX",
    "____mbstate_t_defined",
    "__mbstate_t_defined",
    "M_E",
    "METH_CLASS",
    "METH_COEXIST",
    "METH_FASTCALL",
    "METH_KEYWORDS",
    "METH_METHOD",
    "METH_NOARGS",
    "METH_O",
    "METH_STACKLESS",
    "METH_STATIC",
    "METH_VARARGS",
    "M_LN10",
    "M_LN2",
    "M_LOG10E",
    "M_LOG2E",
    "M_PI",
    "M_PI_2",
    "M_PI_4",
    "MQ_PRIO_MAX",
    "MSG_BATCH",
    "MSG_CMSG_CLOEXEC",
    "MSG_CONFIRM",
    "MSG_CTRUNC",
    "MSG_DONTROUTE",
    "MSG_DONTWAIT",
    "MSG_EOR",
    "MSG_ERRQUEUE",
    "MSG_FASTOPEN",
    "MSG_FIN",
    "MSG_MORE",
    "MSG_NOSIGNAL",
    "MSG_OOB",
    "MSG_PEEK",
    "MSG_PROXY",
    "MSG_RST",
    "MSG_SYN",
    "MSG_TRUNC",
    "MSG_WAITALL",
    "MSG_WAITFORONE",
    "MSG_ZEROCOPY",
    "M_SQRT1_2",
    "M_SQRT2",
    "MVWDELCH_IS_EXPRESSION",
    "NAME_MAX",
    "_NETBSD_SOURCE",
    "__NET_ETHERNET_H",
    "_NET_IF_ARP_H",
    "_NET_IF_H",
    "__NETINET_IF_ETHER_H",
    "_NETINET_TCP_H",
    "NGROUPS_MAX",
    "NOWAIT_LOCK",
    "NR_OPEN",
    "__OFF_T_MATCHES_OFF64_T",
    "__osockaddr_defined",
    "PATH_MAX",
    "PATH_SEP",
    "PATH_SEP_CHAR",
    "_PC_2_SYMLINKS",
    "_PC_ALLOC_SIZE_MIN",
    "_PC_ASYNC_IO",
    "_PC_CHOWN_RESTRICTED",
    "_PC_FILESIZEBITS",
    "PCIE_ADAPTER_COMPAT_INTERFACE",
    "_PC_LINK_MAX",
    "_PC_MAX_CANON",
    "_PC_MAX_INPUT",
    "_PC_NAME_MAX",
    "_PC_NO_TRUNC",
    "_PC_PATH_MAX",
    "_PC_PIPE_BUF",
    "_PC_PRIO_IO",
    "_PC_REC_INCR_XFER_SIZE",
    "_PC_REC_MAX_XFER_SIZE",
    "_PC_REC_MIN_XFER_SIZE",
    "_PC_REC_XFER_ALIGN",
    "_PC_SOCK_MAXBUF",
    "_PC_SYMLINK_MAX",
    "_PC_SYNC_IO",
    "_PC_VDISABLE",
    "__PDP_ENDIAN",
    "PDP_ENDIAN",
    "PF_ALG",
    "PF_APPLETALK",
    "PF_ASH",
    "PF_ATMPVC",
    "PF_ATMSVC",
    "PF_AX25",
    "PF_BLUETOOTH",
    "PF_BRIDGE",
    "PF_CAIF",
    "PF_CAN",
    "PF_DECnet",
    "PF_ECONET",
    "PF_FILE",
    "PF_IB",
    "PF_IEEE802154",
    "PF_INET",
    "PF_INET6",
    "PF_IPX",
    "PF_IRDA",
    "PF_ISDN",
    "PF_IUCV",
    "PF_KCM",
    "PF_KEY",
    "PF_LLC",
    "PF_LOCAL",
    "PF_MAX",
    "PF_MCTP",
    "PF_MPLS",
    "PF_NETBEUI",
    "PF_NETLINK",
    "PF_NETROM",
    "PF_NFC",
    "PF_PACKET",
    "PF_PHONET",
    "PF_PPPOX",
    "PF_QIPCRTR",
    "PF_RDS",
    "PF_ROSE",
    "PF_ROUTE",
    "PF_RXRPC",
    "PF_SECURITY",
    "PF_SMC",
    "PF_SNA",
    "PF_TIPC",
    "PF_UNIX",
    "PF_UNSPEC",
    "PF_VSOCK",
    "PF_WANPIPE",
    "PF_X25",
    "PF_XDP",
    "PIPE_BUF",
    "_POSIX2_BC_BASE_MAX",
    "_POSIX2_BC_DIM_MAX",
    "_POSIX2_BC_SCALE_MAX",
    "_POSIX2_BC_STRING_MAX",
    "_POSIX2_C_BIND",
    "_POSIX2_C_DEV",
    "_POSIX2_CHARCLASS_NAME_MAX",
    "_POSIX2_CHAR_TERM",
    "_POSIX2_COLL_WEIGHTS_MAX",
    "_POSIX2_C_VERSION",
    "_POSIX2_EXPR_NEST_MAX",
    "_POSIX2_LINE_MAX",
    "_POSIX2_LOCALEDEF",
    "_POSIX2_RE_DUP_MAX",
    "_POSIX2_SW_DEV",
    "__POSIX2_THIS_VERSION",
    "_POSIX2_VERSION",
    "_POSIX_ADVISORY_INFO",
    "_POSIX_AIO_LISTIO_MAX",
    "_POSIX_AIO_MAX",
    "_POSIX_ARG_MAX",
    "_POSIX_ASYNCHRONOUS_IO",
    "_POSIX_ASYNC_IO",
    "_POSIX_BARRIERS",
    "_POSIX_CHILD_MAX",
    "_POSIX_CHOWN_RESTRICTED",
    "_POSIX_CLOCKRES_MIN",
    "_POSIX_CLOCK_SELECTION",
    "_POSIX_CPUTIME",
    "_POSIX_C_SOURCE",
    "_POSIX_DELAYTIMER_MAX",
    "_POSIX_FSYNC",
    "_POSIX_HOST_NAME_MAX",
    "_POSIX_IPV6",
    "_POSIX_JOB_CONTROL",
    "_POSIX_LINK_MAX",
    "_POSIX_LOGIN_NAME_MAX",
    "_POSIX_MAPPED_FILES",
    "_POSIX_MAX_CANON",
    "_POSIX_MAX_INPUT",
    "_POSIX_MEMLOCK",
    "_POSIX_MEMLOCK_RANGE",
    "_POSIX_MEMORY_PROTECTION",
    "_POSIX_MESSAGE_PASSING",
    "_POSIX_MONOTONIC_CLOCK",
    "_POSIX_MQ_OPEN_MAX",
    "_POSIX_MQ_PRIO_MAX",
    "_POSIX_NAME_MAX",
    "_POSIX_NGROUPS_MAX",
    "_POSIX_NO_TRUNC",
    "_POSIX_OPEN_MAX",
    "_POSIX_PATH_MAX",
    "_POSIX_PIPE_BUF",
    "_POSIX_PRIORITIZED_IO",
    "_POSIX_PRIORITY_SCHEDULING",
    "_POSIX_PTHREAD_SEMANTICS",
    "_POSIX_RAW_SOCKETS",
    "_POSIX_READER_WRITER_LOCKS",
    "_POSIX_REALTIME_SIGNALS",
    "_POSIX_RE_DUP_MAX",
    "_POSIX_REENTRANT_FUNCTIONS",
    "_POSIX_REGEXP",
    "_POSIX_RTSIG_MAX",
    "_POSIX_SAVED_IDS",
    "_POSIX_SEMAPHORES",
    "_POSIX_SEM_NSEMS_MAX",
    "_POSIX_SEM_VALUE_MAX",
    "_POSIX_SHARED_MEMORY_OBJECTS",
    "_POSIX_SHELL",
    "_POSIX_SIGQUEUE_MAX",
    "_POSIX_SOURCE",
    "_POSIX_SPAWN",
    "_POSIX_SPIN_LOCKS",
    "_POSIX_SPORADIC_SERVER",
    "_POSIX_SSIZE_MAX",
    "_POSIX_STREAM_MAX",
    "_POSIX_SYMLINK_MAX",
    "_POSIX_SYMLOOP_MAX",
    "_POSIX_SYNCHRONIZED_IO",
    "_POSIX_THREAD_ATTR_STACKADDR",
    "_POSIX_THREAD_ATTR_STACKSIZE",
    "_POSIX_THREAD_CPUTIME",
    "_POSIX_THREAD_DESTRUCTOR_ITERATIONS",
    "_POSIX_THREAD_KEYS_MAX",
    "_POSIX_THREAD_PRIO_INHERIT",
    "_POSIX_THREAD_PRIO_PROTECT",
    "_POSIX_THREAD_PRIORITY_SCHEDULING",
    "_POSIX_THREAD_PROCESS_SHARED",
    "_POSIX_THREAD_ROBUST_PRIO_INHERIT",
    "_POSIX_THREAD_ROBUST_PRIO_PROTECT",
    "_POSIX_THREADS",
    "_POSIX_THREAD_SAFE_FUNCTIONS",
    "_POSIX_THREAD_SPORADIC_SERVER",
    "_POSIX_THREAD_THREADS_MAX",
    "_POSIX_TIMEOUTS",
    "_POSIX_TIMER_MAX",
    "_POSIX_TIMERS",
    "_POSIX_TRACE",
    "_POSIX_TRACE_EVENT_FILTER",
    "_POSIX_TRACE_INHERIT",
    "_POSIX_TRACE_LOG",
    "_POSIX_TTY_NAME_MAX",
    "_POSIX_TYPED_MEMORY_OBJECTS",
    "_POSIX_TZNAME_MAX",
    "_POSIX_V6_LP64_OFF64",
    "_POSIX_V6_LPBIG_OFFBIG",
    "_POSIX_V7_LP64_OFF64",
    "_POSIX_V7_LPBIG_OFFBIG",
    "_POSIX_VDISABLE",
    "_POSIX_VERSION",
    "__PRI64_PREFIX",
    "PRId16",
    "PRId32",
    "PRId64",
    "PRId8",
    "PRIdFAST16",
    "PRIdFAST32",
    "PRIdFAST64",
    "PRIdFAST8",
    "PRIdLEAST16",
    "PRIdLEAST32",
    "PRIdLEAST64",
    "PRIdLEAST8",
    "PRIdMAX",
    "PRIdPTR",
    "PRIi16",
    "PRIi32",
    "PRIi64",
    "PRIi8",
    "PRIiFAST16",
    "PRIiFAST32",
    "PRIiFAST64",
    "PRIiFAST8",
    "PRIiLEAST16",
    "PRIiLEAST32",
    "PRIiLEAST64",
    "PRIiLEAST8",
    "PRIiMAX",
    "PRIiPTR",
    "PRIo16",
    "PRIo32",
    "PRIo64",
    "PRIo8",
    "PRIoFAST16",
    "PRIoFAST32",
    "PRIoFAST64",
    "PRIoFAST8",
    "PRIoLEAST16",
    "PRIoLEAST32",
    "PRIoLEAST64",
    "PRIoLEAST8",
    "PRIoMAX",
    "PRIoPTR",
    "__PRIPTR_PREFIX",
    "PRIu16",
    "PRIu32",
    "PRIu64",
    "PRIu8",
    "PRIuFAST16",
    "PRIuFAST32",
    "PRIuFAST64",
    "PRIuFAST8",
    "PRIuLEAST16",
    "PRIuLEAST32",
    "PRIuLEAST64",
    "PRIuLEAST8",
    "PRIuMAX",
    "PRIuPTR",
    "PRIx16",
    "PRIX16",
    "PRIx32",
    "PRIX32",
    "PRIx64",
    "PRIX64",
    "PRIx8",
    "PRIX8",
    "PRIxFAST16",
    "PRIXFAST16",
    "PRIxFAST32",
    "PRIXFAST32",
    "PRIxFAST64",
    "PRIXFAST64",
    "PRIxFAST8",
    "PRIXFAST8",
    "PRIxLEAST16",
    "PRIXLEAST16",
    "PRIxLEAST32",
    "PRIXLEAST32",
    "PRIxLEAST64",
    "PRIXLEAST64",
    "PRIxLEAST8",
    "PRIXLEAST8",
    "PRIxMAX",
    "PRIXMAX",
    "PRIxPTR",
    "PRIXPTR",
    "PTHREAD_BARRIER_SERIAL_THREAD",
    "PTHREAD_CANCEL_ASYNCHRONOUS",
    "PTHREAD_CANCEL_DEFERRED",
    "PTHREAD_CANCEL_DISABLE",
    "PTHREAD_CANCEL_ENABLE",
    "PTHREAD_CREATE_DETACHED",
    "PTHREAD_CREATE_JOINABLE",
    "PTHREAD_DESTRUCTOR_ITERATIONS",
    "PTHREAD_EXPLICIT_SCHED",
    "_PTHREAD_H",
    "PTHREAD_INHERIT_SCHED",
    "PTHREAD_KEYS_MAX",
    "PTHREAD_KEY_T_IS_COMPATIBLE_WITH_INT",
    "PTHREAD_MUTEX_ADAPTIVE_NP",
    "PTHREAD_MUTEX_DEFAULT",
    "PTHREAD_MUTEX_ERRORCHECK",
    "PTHREAD_MUTEX_ERRORCHECK_NP",
    "__PTHREAD_MUTEX_HAVE_PREV",
    "PTHREAD_MUTEX_NORMAL",
    "PTHREAD_MUTEX_RECURSIVE",
    "PTHREAD_MUTEX_RECURSIVE_NP",
    "PTHREAD_MUTEX_ROBUST",
    "PTHREAD_MUTEX_ROBUST_NP",
    "PTHREAD_MUTEX_STALLED",
    "PTHREAD_MUTEX_STALLED_NP",
    "PTHREAD_MUTEX_TIMED_NP",
    "PTHREAD_ONCE_INIT",
    "PTHREAD_PRIO_INHERIT",
    "PTHREAD_PRIO_NONE",
    "PTHREAD_PRIO_PROTECT",
    "PTHREAD_PROCESS_PRIVATE",
    "PTHREAD_PROCESS_SHARED",
    "PTHREAD_SCOPE_PROCESS",
    "PTHREAD_SCOPE_SYSTEM",
    "PTHREAD_STACK_MIN",
    "PTHREAD_SYSTEM_SCHED_SUPPORTED",
    "P_tmpdir",
    "PTRDIFF_MIN",
    "*PY*",
    "*Py*",
    "RAND_MAX",
    "RE_DUP_MAX",
    "RISCV_IMSIC_INTERFACE",
    "RISCV_SIGNAL_SGEIP_INTERFACE",
    "__RLIM_T_MATCHES_RLIM64_T",
    "R_OK",
    "RTLD_BINDING_MASK",
    "RTLD_DEEPBIND",
    "RTLD_LAZY",
    "RTLD_NODELETE",
    "RTLD_NOLOAD",
    "RTSIG_MAX",
    "S_BLKSIZE",
    "_SC_2_C_BIND",
    "_SC_2_C_DEV",
    "_SC_2_CHAR_TERM",
    "_SC_2_C_VERSION",
    "_SC_2_FORT_DEV",
    "_SC_2_FORT_RUN",
    "_SC_2_LOCALEDEF",
    "_SC_2_PBS",
    "_SC_2_PBS_ACCOUNTING",
    "_SC_2_PBS_CHECKPOINT",
    "_SC_2_PBS_LOCATE",
    "_SC_2_PBS_MESSAGE",
    "_SC_2_PBS_TRACK",
    "_SC_2_SW_DEV",
    "_SC_2_UPE",
    "_SC_2_VERSION",
    "_SC_ADVISORY_INFO",
    "_SC_AIO_LISTIO_MAX",
    "_SC_AIO_MAX",
    "_SC_AIO_PRIO_DELTA_MAX",
    "_SC_ARG_MAX",
    "_SC_ASYNCHRONOUS_IO",
    "_SC_ATEXIT_MAX",
    "_SC_AVPHYS_PAGES",
    "_SC_BARRIERS",
    "_SC_BASE",
    "_SC_BC_BASE_MAX",
    "_SC_BC_DIM_MAX",
    "_SC_BC_SCALE_MAX",
    "_SC_BC_STRING_MAX",
    "_SC_CHAR_BIT",
    "_SC_CHARCLASS_NAME_MAX",
    "_SC_CHAR_MAX",
    "_SC_CHAR_MIN",
    "_SC_CHILD_MAX",
    "_SC_C_LANG_SUPPORT",
    "_SC_C_LANG_SUPPORT_R",
    "_SC_CLK_TCK",
    "_SC_CLOCK_SELECTION",
    "_SC_COLL_WEIGHTS_MAX",
    "_SC_CPUTIME",
    "_SC_DELAYTIMER_MAX",
    "_SC_DEVICE_IO",
    "_SC_DEVICE_SPECIFIC",
    "_SC_DEVICE_SPECIFIC_R",
    "_SC_EQUIV_CLASS_MAX",
    "_SC_EXPR_NEST_MAX",
    "_SC_FD_MGMT",
    "_SC_FIFO",
    "_SC_FILE_ATTRIBUTES",
    "_SC_FILE_LOCKING",
    "_SC_FILE_SYSTEM",
    "_SC_FSYNC",
    "_SC_GETGR_R_SIZE_MAX",
    "_SC_GETPW_R_SIZE_MAX",
    "SCHED_FIFO",
    "_SCHED_H",
    "SCHED_OTHER",
    "SCHED_RR",
    "_SC_HOST_NAME_MAX",
    "_SC_INT_MAX",
    "_SC_INT_MIN",
    "_SC_IOV_MAX",
    "_SC_IPV6",
    "_SC_JOB_CONTROL",
    "_SC_LEVEL1_DCACHE_ASSOC",
    "_SC_LEVEL1_DCACHE_LINESIZE",
    "_SC_LEVEL1_DCACHE_SIZE",
    "_SC_LEVEL1_ICACHE_ASSOC",
    "_SC_LEVEL1_ICACHE_LINESIZE",
    "_SC_LEVEL1_ICACHE_SIZE",
    "_SC_LEVEL2_CACHE_ASSOC",
    "_SC_LEVEL2_CACHE_LINESIZE",
    "_SC_LEVEL2_CACHE_SIZE",
    "_SC_LEVEL3_CACHE_ASSOC",
    "_SC_LEVEL3_CACHE_LINESIZE",
    "_SC_LEVEL3_CACHE_SIZE",
    "_SC_LEVEL4_CACHE_ASSOC",
    "_SC_LEVEL4_CACHE_LINESIZE",
    "_SC_LEVEL4_CACHE_SIZE",
    "_SC_LINE_MAX",
    "_SC_LOGIN_NAME_MAX",
    "_SC_LONG_BIT",
    "_SC_MAPPED_FILES",
    "_SC_MB_LEN_MAX",
    "_SC_MEMLOCK",
    "_SC_MEMLOCK_RANGE",
    "_SC_MEMORY_PROTECTION",
    "_SC_MESSAGE_PASSING",
    "_SC_MINSIGSTKSZ",
    "_SC_MONOTONIC_CLOCK",
    "_SC_MQ_OPEN_MAX",
    "_SC_MQ_PRIO_MAX",
    "SCM_RIGHTS",
    "SCM_TIMESTAMP",
    "SCM_TIMESTAMPING",
    "SCM_TIMESTAMPING_OPT_STATS",
    "SCM_TIMESTAMPING_PKTINFO",
    "SCM_TIMESTAMPNS",
    "SCM_TXTIME",
    "_SC_MULTI_PROCESS",
    "SCM_WIFI_STATUS",
    "SCNd16",
    "SCNd32",
    "SCNd64",
    "SCNd8",
    "SCNdFAST16",
    "SCNdFAST32",
    "SCNdFAST64",
    "SCNdFAST8",
    "SCNdLEAST16",
    "SCNdLEAST32",
    "SCNdLEAST64",
    "SCNdLEAST8",
    "SCNdMAX",
    "SCNdPTR",
    "_SC_NETWORKING",
    "_SC_NGROUPS_MAX",
    "SCNi16",
    "SCNi32",
    "SCNi64",
    "SCNi8",
    "SCNiFAST16",
    "SCNiFAST32",
    "SCNiFAST64",
    "SCNiFAST8",
    "SCNiLEAST16",
    "SCNiLEAST32",
    "SCNiLEAST64",
    "SCNiLEAST8",
    "SCNiMAX",
    "SCNiPTR",
    "_SC_NL_ARGMAX",
    "_SC_NL_LANGMAX",
    "_SC_NL_MSGMAX",
    "_SC_NL_NMAX",
    "_SC_NL_SETMAX",
    "_SC_NL_TEXTMAX",
    "SCNo16",
    "SCNo32",
    "SCNo64",
    "SCNo8",
    "SCNoFAST16",
    "SCNoFAST32",
    "SCNoFAST64",
    "SCNoFAST8",
    "SCNoLEAST16",
    "SCNoLEAST32",
    "SCNoLEAST64",
    "SCNoLEAST8",
    "SCNoMAX",
    "SCNoPTR",
    "_SC_NPROCESSORS_CONF",
    "_SC_NPROCESSORS_ONLN",
    "SCNu16",
    "SCNu32",
    "SCNu64",
    "SCNu8",
    "SCNuFAST16",
    "SCNuFAST32",
    "SCNuFAST64",
    "SCNuFAST8",
    "SCNuLEAST16",
    "SCNuLEAST32",
    "SCNuLEAST64",
    "SCNuLEAST8",
    "SCNuMAX",
    "SCNuPTR",
    "SCNx16",
    "SCNx32",
    "SCNx64",
    "SCNx8",
    "SCNxFAST16",
    "SCNxFAST32",
    "SCNxFAST64",
    "SCNxFAST8",
    "SCNxLEAST16",
    "SCNxLEAST32",
    "SCNxLEAST64",
    "SCNxLEAST8",
    "SCNxMAX",
    "SCNxPTR",
    "_SC_NZERO",
    "_SC_OPEN_MAX",
    "_SC_PAGESIZE",
    "_SC_PASS_MAX",
    "_SC_PHYS_PAGES",
    "_SC_PII",
    "_SC_PII_INTERNET",
    "_SC_PII_INTERNET_DGRAM",
    "_SC_PII_INTERNET_STREAM",
    "_SC_PII_OSI",
    "_SC_PII_OSI_CLTS",
    "_SC_PII_OSI_COTS",
    "_SC_PII_OSI_M",
    "_SC_PII_SOCKET",
    "_SC_PII_XTI",
    "_SC_PIPE",
    "_SC_POLL",
    "_SC_PRIORITIZED_IO",
    "_SC_PRIORITY_SCHEDULING",
    "_SC_RAW_SOCKETS",
    "_SC_READER_WRITER_LOCKS",
    "_SC_REALTIME_SIGNALS",
    "_SC_RE_DUP_MAX",
    "_SC_REGEXP",
    "_SC_REGEX_VERSION",
    "_SC_RTSIG_MAX",
    "_SC_SAVED_IDS",
    "_SC_SCHAR_MAX",
    "_SC_SCHAR_MIN",
    "_SC_SELECT",
    "_SC_SEMAPHORES",
    "_SC_SEM_NSEMS_MAX",
    "_SC_SEM_VALUE_MAX",
    "_SC_SHARED_MEMORY_OBJECTS",
    "_SC_SHELL",
    "_SC_SHRT_MAX",
    "_SC_SHRT_MIN",
    "_SC_SIGNALS",
    "_SC_SIGQUEUE_MAX",
    "_SC_SIGSTKSZ",
    "_SC_SINGLE_PROCESS",
    "_SC_SPAWN",
    "_SC_SPIN_LOCKS",
    "_SC_SPORADIC_SERVER",
    "_SC_SSIZE_MAX",
    "_SC_SS_REPL_MAX",
    "_SC_STREAM_MAX",
    "_SC_STREAMS",
    "_SC_SYMLOOP_MAX",
    "_SC_SYNCHRONIZED_IO",
    "_SC_SYSTEM_DATABASE",
    "_SC_SYSTEM_DATABASE_R",
    "_SC_THREAD_ATTR_STACKADDR",
    "_SC_THREAD_ATTR_STACKSIZE",
    "_SC_THREAD_CPUTIME",
    "_SC_THREAD_KEYS_MAX",
    "_SC_THREAD_PRIO_INHERIT",
    "_SC_THREAD_PRIO_PROTECT",
    "_SC_THREAD_PROCESS_SHARED",
    "_SC_THREADS",
    "_SC_THREAD_SAFE_FUNCTIONS",
    "_SC_THREAD_SPORADIC_SERVER",
    "_SC_THREAD_STACK_MIN",
    "_SC_THREAD_THREADS_MAX",
    "_SC_TIMEOUTS",
    "_SC_TIMER_MAX",
    "_SC_TIMERS",
    "_SC_T_IOV_MAX",
    "_SC_TRACE",
    "_SC_TRACE_EVENT_FILTER",
    "_SC_TRACE_EVENT_NAME_MAX",
    "_SC_TRACE_INHERIT",
    "_SC_TRACE_LOG",
    "_SC_TRACE_NAME_MAX",
    "_SC_TRACE_SYS_MAX",
    "_SC_TRACE_USER_EVENT_MAX",
    "_SC_TTY_NAME_MAX",
    "_SC_TYPED_MEMORY_OBJECTS",
    "_SC_TZNAME_MAX",
    "_SC_UCHAR_MAX",
    "_SC_UINT_MAX",
    "_SC_UIO_MAXIOV",
    "_SC_ULONG_MAX",
    "_SC_USER_GROUPS",
    "_SC_USER_GROUPS_R",
    "_SC_USHRT_MAX",
    "_SC_V6_ILP32_OFF32",
    "_SC_V6_ILP32_OFFBIG",
    "_SC_V6_LP64_OFF64",
    "_SC_V6_LPBIG_OFFBIG",
    "_SC_V7_ILP32_OFF32",
    "_SC_V7_ILP32_OFFBIG",
    "_SC_V7_LP64_OFF64",
    "_SC_V7_LPBIG_OFFBIG",
    "_SC_VERSION",
    "_SC_WORD_BIT",
    "_SC_XBS5_ILP32_OFF32",
    "_SC_XBS5_ILP32_OFFBIG",
    "_SC_XBS5_LP64_OFF64",
    "_SC_XBS5_LPBIG_OFFBIG",
    "_SC_XOPEN_CRYPT",
    "_SC_XOPEN_ENH_I18N",
    "_SC_XOPEN_LEGACY",
    "_SC_XOPEN_REALTIME",
    "_SC_XOPEN_REALTIME_THREADS",
    "_SC_XOPEN_SHM",
    "_SC_XOPEN_STREAMS",
    "_SC_XOPEN_UNIX",
    "_SC_XOPEN_VERSION",
    "_SC_XOPEN_XCU_VERSION",
    "_SC_XOPEN_XPG2",
    "_SC_XOPEN_XPG3",
    "_SC_XOPEN_XPG4",
    "SEEK_CUR",
    "SEEK_END",
    "SEEK_SET",
    "SEM_VALUE_MAX",
    "SHUT_RD",
    "SHUT_RDWR",
    "SHUT_WR",
    "__S_IEXEC",
    "S_IEXEC",
    "__S_IFBLK",
    "S_IFBLK",
    "__S_IFCHR",
    "S_IFCHR",
    "__S_IFDIR",
    "S_IFDIR",
    "__S_IFIFO",
    "S_IFIFO",
    "__S_IFLNK",
    "S_IFLNK",
    "__S_IFMT",
    "S_IFMT",
    "__S_IFREG",
    "S_IFREG",
    "__S_IFSOCK",
    "S_IFSOCK",
    "SIG_ATOMIC_MAX",
    "SIG_ATOMIC_MIN",
    "__sigset_t_defined",
    "SIMICS_HOST_TYPE",
    "SIOCATMARK",
    "SIOCGPGRP",
    "SIOCGSTAMPNS_OLD",
    "SIOCGSTAMP_OLD",
    "SIOCSPGRP",
    "__S_IREAD",
    "S_IREAD",
    "S_IRGRP",
    "S_IROTH",
    "S_IRUSR",
    "S_IRWXG",
    "S_IRWXO",
    "S_IRWXU",
    "__S_ISGID",
    "S_ISGID",
    "__S_ISUID",
    "S_ISUID",
    "__S_ISVTX",
    "S_ISVTX",
    "S_IWGRP",
    "S_IWOTH",
    "__S_IWRITE",
    "S_IWRITE",
    "S_IWUSR",
    "S_IXGRP",
    "S_IXOTH",
    "S_IXUSR",
    "SIZE_MAX",
    "SIZEOF__BOOL",
    "SIZEOF_DOUBLE",
    "SIZEOF_FLOAT",
    "SIZEOF_FPOS_T",
    "SIZEOF_INT",
    "SIZEOF_LONG",
    "SIZEOF_LONG_DOUBLE",
    "SIZEOF_LONG_LONG",
    "SIZEOF_OFF_T",
    "SIZEOF_PID_T",
    "__SIZEOF_PTHREAD_ATTR_T",
    "__SIZEOF_PTHREAD_BARRIERATTR_T",
    "__SIZEOF_PTHREAD_BARRIER_T",
    "__SIZEOF_PTHREAD_CONDATTR_T",
    "__SIZEOF_PTHREAD_COND_T",
    "SIZEOF_PTHREAD_KEY_T",
    "__SIZEOF_PTHREAD_MUTEXATTR_T",
    "__SIZEOF_PTHREAD_MUTEX_T",
    "__SIZEOF_PTHREAD_RWLOCKATTR_T",
    "__SIZEOF_PTHREAD_RWLOCK_T",
    "SIZEOF_PTHREAD_T",
    "SIZEOF_PY_HASH_T",
    "SIZEOF_PY_UHASH_T",
    "SIZEOF_SHORT",
    "SIZEOF_SIZE_T",
    "SIZEOF_TIME_T",
    "SIZEOF_UINTPTR_T",
    "SIZEOF_VOID_P",
    "SIZEOF_WCHAR_T",
    "SO_ACCEPTCONN",
    "SO_ATTACH_BPF",
    "SO_ATTACH_FILTER",
    "SO_ATTACH_REUSEPORT_CBPF",
    "SO_ATTACH_REUSEPORT_EBPF",
    "SO_BINDTODEVICE",
    "SO_BINDTOIFINDEX",
    "SO_BPF_EXTENSIONS",
    "SO_BROADCAST",
    "SO_BSDCOMPAT",
    "SO_BUF_LOCK",
    "SO_BUSY_POLL",
    "SO_BUSY_POLL_BUDGET",
    "SO_CNX_ADVICE",
    "SO_COOKIE",
    "SO_DEBUG",
    "SO_DETACH_BPF",
    "SO_DETACH_FILTER",
    "SO_DETACH_REUSEPORT_BPF",
    "SO_DOMAIN",
    "SO_DONTROUTE",
    "SO_ERROR",
    "SO_GET_FILTER",
    "SO_INCOMING_CPU",
    "SO_INCOMING_NAPI_ID",
    "SO_KEEPALIVE",
    "SOL_AAL",
    "SOL_ALG",
    "SOL_ATM",
    "SOL_BLUETOOTH",
    "SOL_CAIF",
    "SOL_DCCP",
    "SOL_DECNET",
    "SO_LINGER",
    "SOL_IRDA",
    "SOL_IUCV",
    "SOL_KCM",
    "SOL_LLC",
    "SOL_MCTP",
    "SOL_MPTCP",
    "SOL_NETBEUI",
    "SOL_NETLINK",
    "SOL_NFC",
    "SO_LOCK_FILTER",
    "SOL_PACKET",
    "SOL_PNPIPE",
    "SOL_PPPOL2TP",
    "SOL_RAW",
    "SOL_RDS",
    "SOL_RXRPC",
    "SOL_SMC",
    "SOL_SOCKET",
    "SOL_TCP",
    "SOL_TIPC",
    "SOL_TLS",
    "SOL_X25",
    "SOL_XDP",
    "SO_MARK",
    "SOMAXCONN",
    "SO_MAX_PACING_RATE",
    "SO_MEMINFO",
    "SO_NETNS_COOKIE",
    "SO_NO_CHECK",
    "SO_NOFCS",
    "SO_OOBINLINE",
    "SO_PASSCRED",
    "SO_PASSPIDFD",
    "SO_PASSSEC",
    "SO_PEEK_OFF",
    "SO_PEERCRED",
    "SO_PEERGROUPS",
    "SO_PEERNAME",
    "SO_PEERPIDFD",
    "SO_PEERSEC",
    "SO_PREFER_BUSY_POLL",
    "SO_PRIORITY",
    "SO_PROTOCOL",
    "SO_RCVBUF",
    "SO_RCVBUFFORCE",
    "SO_RCVLOWAT",
    "SO_RCVMARK",
    "SO_RCVTIMEO",
    "SO_RCVTIMEO_NEW",
    "SO_RCVTIMEO_OLD",
    "SO_RESERVE_MEM",
    "SO_REUSEADDR",
    "SO_REUSEPORT",
    "SO_RXQ_OVFL",
    "SO_SECURITY_AUTHENTICATION",
    "SO_SECURITY_ENCRYPTION_NETWORK",
    "SO_SECURITY_ENCRYPTION_TRANSPORT",
    "SO_SELECT_ERR_QUEUE",
    "SO_SFX",
    "SO_SNDBUF",
    "SO_SNDBUFFORCE",
    "SO_SNDLOWAT",
    "SO_SNDTIMEO",
    "SO_SNDTIMEO_NEW",
    "SO_SNDTIMEO_OLD",
    "SO_TIMESTAMP",
    "SO_TIMESTAMPING",
    "SO_TIMESTAMPING_NEW",
    "SO_TIMESTAMPING_OLD",
    "SO_TIMESTAMP_NEW",
    "SO_TIMESTAMPNS",
    "SO_TIMESTAMPNS_NEW",
    "SO_TIMESTAMPNS_OLD",
    "SO_TIMESTAMP_OLD",
    "SO_TXREHASH",
    "SO_TXTIME",
    "SO_TYPE",
    "SO_WIFI_STATUS",
    "SO_ZEROCOPY",
    "_SS_SIZE",
    "SSTATE_INTERNED_IMMORTAL",
    "SSTATE_INTERNED_MORTAL",
    "SSTATE_NOT_INTERNED",
    "__STATFS_MATCHES_STATFS64",
    "STDC_HEADERS",
    "__STDC_IEC_559__",
    "__STDC_IEC_559_COMPLEX__",
    "__STDC_IEC_60559_BFP__",
    "__STDC_IEC_60559_COMPLEX__",
    "__STDC_ISO_10646__",
    "_STDC_PREDEF_H",
    "STDERR_FILENO",
    "STDIN_FILENO",
    "_STDINT_H",
    "_STDIO_H",
    "_STDLIB_H",
    "STDOUT_FILENO",
    "_STRING_H",
    "_STRINGS_H",
    "__struct_FILE_defined",
    "_STRUCT_TIMESPEC",
    "__struct_tm_defined",
    "__SYSCALL_WORDSIZE",
    "_SYS_CDEFS_H",
    "_SYS_SELECT_H",
    "SYS_SELECT_WITH_SYS_TIME",
    "_SYS_SOCKET_H",
    "_SYS_STAT_H",
    "_SYS_TIME_H",
    "_SYS_TYPES_H",
    "_TANDEM_SOURCE",
    "TCP_CC_INFO",
    "TCP_CLOSE",
    "TCP_CLOSE_WAIT",
    "TCP_CLOSING",
    "TCP_CM_INQ",
    "TCP_CONGESTION",
    "TCP_COOKIE_IN_ALWAYS",
    "TCP_COOKIE_MAX",
    "TCP_COOKIE_MIN",
    "TCP_COOKIE_OUT_NEVER",
    "TCP_COOKIE_PAIR_SIZE",
    "TCP_COOKIE_TRANSACTIONS",
    "TCP_CORK",
    "TCP_DEFER_ACCEPT",
    "TCP_ESTABLISHED",
    "TCP_FASTOPEN",
    "TCP_FASTOPEN_CONNECT",
    "TCP_FASTOPEN_KEY",
    "TCP_FASTOPEN_NO_COOKIE",
    "TCP_FIN_WAIT1",
    "TCP_FIN_WAIT2",
    "TCP_INFO",
    "TCP_INQ",
    "TCPI_OPT_ECN",
    "TCPI_OPT_ECN_SEEN",
    "TCPI_OPT_SACK",
    "TCPI_OPT_SYN_DATA",
    "TCPI_OPT_TIMESTAMPS",
    "TCPI_OPT_WSCALE",
    "TCP_KEEPCNT",
    "TCP_KEEPIDLE",
    "TCP_KEEPINTVL",
    "TCP_LAST_ACK",
    "TCP_LINGER2",
    "TCP_LISTEN",
    "TCP_MAXSEG",
    "TCP_MAXWIN",
    "TCP_MAX_WINSHIFT",
    "TCP_MD5SIG",
    "TCP_MD5SIG_EXT",
    "TCP_MD5SIG_FLAG_PREFIX",
    "TCP_MD5SIG_MAXKEYLEN",
    "TCP_MSS",
    "TCP_MSS_DEFAULT",
    "TCP_MSS_DESIRED",
    "TCP_NODELAY",
    "TCP_NO_QUEUE",
    "TCP_NOTSENT_LOWAT",
    "TCPOLEN_MAXSEG",
    "TCPOLEN_SACK_PERMITTED",
    "TCPOLEN_TIMESTAMP",
    "TCPOLEN_TSTAMP_APPA",
    "TCPOLEN_WINDOW",
    "TCPOPT_EOL",
    "TCPOPT_MAXSEG",
    "TCPOPT_NOP",
    "TCPOPT_SACK",
    "TCPOPT_SACK_PERMITTED",
    "TCPOPT_TIMESTAMP",
    "TCPOPT_TSTAMP_HDR",
    "TCPOPT_WINDOW",
    "TCP_QUEUE_SEQ",
    "TCP_QUEUES_NR",
    "TCP_QUICKACK",
    "TCP_RECV_QUEUE",
    "TCP_REPAIR",
    "TCP_REPAIR_OFF",
    "TCP_REPAIR_OFF_NO_WP",
    "TCP_REPAIR_ON",
    "TCP_REPAIR_OPTIONS",
    "TCP_REPAIR_QUEUE",
    "TCP_REPAIR_WINDOW",
    "TCP_SAVED_SYN",
    "TCP_SAVE_SYN",
    "TCP_S_DATA_IN",
    "TCP_S_DATA_OUT",
    "TCP_SEND_QUEUE",
    "TCP_SYNCNT",
    "TCP_SYN_RECV",
    "TCP_SYN_SENT",
    "TCP_THIN_DUPACK",
    "TCP_THIN_LINEAR_TIMEOUTS",
    "TCP_TIMESTAMP",
    "TCP_TIME_WAIT",
    "TCP_TX_DELAY",
    "TCP_ULP",
    "TCP_USER_TIMEOUT",
    "TCP_WINDOW_CLAMP",
    "TCP_ZEROCOPY_RECEIVE",
    "TH_ACK",
    "TH_FIN",
    "TH_PUSH",
    "_THREAD_MUTEX_INTERNAL_H",
    "_THREAD_SHARED_TYPES_H",
    "TH_RST",
    "TH_SYN",
    "TH_URG",
    "_TIME_H",
    "TIMER_ABSTIME",
    "__timer_t_defined",
    "__TIMESIZE",
    "__time_t_defined",
    "TIME_UTC",
    "__timeval_defined",
    "TIME_WITH_SYS_TIME",
    "TMP_MAX",
    "true_",
    "TTY_NAME_MAX",
    "__UAPI_DEF_ETHHDR",
    "UINT16_MAX",
    "UINT32_MAX",
    "UINT8_MAX",
    "UINT_FAST16_MAX",
    "UINT_FAST32_MAX",
    "UINT_FAST8_MAX",
    "UINT_LEAST16_MAX",
    "UINT_LEAST32_MAX",
    "UINT_LEAST8_MAX",
    "UINTPTR_MAX",
    "_UNISTD_H",
    "__USE_ATFILE",
    "USE_BINFMT_ELF",
    "USE_COMPUTED_GOTOS",
    "__USE_FORTIFY_LEVEL",
    "__USE_ISOC11",
    "__USE_ISOC95",
    "__USE_ISOC99",
    "__USE_MISC",
    "__USE_POSIX",
    "__USE_POSIX199309",
    "__USE_POSIX199506",
    "__USE_POSIX2",
    "__USE_POSIX_IMPLICITLY",
    "__USE_XOPEN2K",
    "__USE_XOPEN2K8",
    "UTIME_NOW",
    "UTIME_OMIT",
    "WAIT_LOCK",
    "__WALL",
    "_WCHAR_H",
    "__WCLONE",
    "__W_CONTINUED",
    "WCONTINUED",
    "__WCOREFLAG",
    "WEOF",
    "WEXITED",
    "WINDOW_HAS_FLAGS",
    "WINT_MAX",
    "WINT_MIN",
    "_WINT_T",
    "__wint_t_defined",
    "WITH_DECIMAL_CONTEXTVAR",
    "WITH_DOC_STRINGS",
    "WITH_PYMALLOC",
    "WNOHANG",
    "__WNOTHREAD",
    "WNOWAIT",
    "W_OK",
    "__WORDSIZE",
    "__WORDSIZE_TIME64_COMPAT32",
    "WSTOPPED",
    "WUNTRACED",
    "XATTR_LIST_MAX",
    "XATTR_NAME_MAX",
    "XATTR_SIZE_MAX",
    "_XBS5_LP64_OFF64",
    "_XBS5_LPBIG_OFFBIG",
    "X_OK",
    "_XOPEN_ENH_I18N",
    "_XOPEN_LEGACY",
    "_XOPEN_REALTIME",
    "_XOPEN_REALTIME_THREADS",
    "_XOPEN_SHM",
    "_XOPEN_SOURCE",
    "_XOPEN_SOURCE_EXTENDED",
    "_XOPEN_UNIX",
    "_XOPEN_VERSION",
    "_XOPEN_XCU_VERSION",
    "_XOPEN_XPG2",
    "_XOPEN_XPG3",
    "_XOPEN_XPG4",
];

/// Generated with something like:
///
/// rg -Nor '$1' "fn ([A-Za-z0-9_]+)" target/debug/build/simics-api-sys-ae6e3cb0e0e0db62/out/bindings-auto.rs | sort | uniq > /tmp/nokeep-func.txt
/// rg -Nor '$1' "fn ([A-Za-z0-9_]+)" target/debug/build/simics-api-sys-ae6e3cb0e0e0db62/out/bindings-auto.rs | xargs -i bash -c 'if rg -U --multiline-dotall -g "!host-info.h" -g "!module-host-config.h" -g "!base-types.h" -g "!python-header.h" "EXPORTED.*{}" /home/rhart/simics/simics-6.0.169/src/include | rg -vq "undef|ifdef"; then echo "{}"; fi' | sort | uniq > /tmp/keep-func.txt
/// comm -23 /tmp/nokeep-func.txt /tmp/keep-func.txt | rg -v "bindgen|SIM|VT|vt|sim|mm" | xclip -selection clipboard
const FUNCS_BLOCKLIST: &[&str; 1310] = &[
    "a64l",
    "access_linear",
    "acct",
    "__acos",
    "acos",
    "__acosf",
    "acosf",
    "__acosh",
    "acosh",
    "__acoshf",
    "acoshf",
    "__acoshl",
    "acoshl",
    "__acosl",
    "acosl",
    "adjtime",
    "alarm",
    "aligned_alloc",
    "arc4random",
    "arc4random_buf",
    "arc4random_uniform",
    "ascii",
    "asctime",
    "asctime_r",
    "__asin",
    "asin",
    "__asinf",
    "asinf",
    "__asinh",
    "asinh",
    "__asinhf",
    "asinhf",
    "__asinhl",
    "asinhl",
    "__asinl",
    "asinl",
    "as_mut_ptr",
    "as_mut_slice",
    "__asprintf",
    "asprintf",
    "as_ptr",
    "__assert",
    "assert_error",
    "__assert_fail",
    "__assert_perror_fail",
    "as_slice",
    "__atan",
    "atan",
    "__atan2",
    "atan2",
    "__atan2f",
    "atan2f",
    "__atan2l",
    "atan2l",
    "__atanf",
    "atanf",
    "__atanh",
    "atanh",
    "__atanhf",
    "atanhf",
    "__atanhl",
    "atanhl",
    "__atanl",
    "atanl",
    "atexit",
    "atof",
    "atoi",
    "atol",
    "atoll",
    "at_quick_exit",
    "bcmp",
    "bcopy",
    "bitand",
    "bitand_assign",
    "bitor",
    "bitor_assign",
    "block_STC",
    "brk",
    "bsearch",
    "btowc",
    "bzero",
    "cache_coherency",
    "calloc",
    "__cbrt",
    "cbrt",
    "__cbrtf",
    "cbrtf",
    "__cbrtl",
    "cbrtl",
    "__ceil",
    "ceil",
    "__ceilf",
    "ceilf",
    "__ceill",
    "ceill",
    "chdir",
    "chmod",
    "chown",
    "chroot",
    "clearenv",
    "clearerr",
    "clearerr_unlocked",
    "clear_interval",
    "clock_getcpuclockid",
    "clock_getres",
    "clock_gettime",
    "clock_nanosleep",
    "clock_settime",
    "closefrom",
    "__cmsg_nxthdr",
    "compact",
    "confstr",
    "__copysign",
    "copysign",
    "__copysignf",
    "copysignf",
    "__copysignl",
    "copysignl",
    "__cos",
    "__cosf",
    "cosf",
    "__cosh",
    "cosh",
    "__coshf",
    "coshf",
    "__coshl",
    "coshl",
    "__cosl",
    "cosl",
    "crypt",
    "ctermid",
    "ctime",
    "ctime_r",
    "__ctype_b_loc",
    "__ctype_get_mb_cur_max",
    "__ctype_tolower_loc",
    "__ctype_toupper_loc",
    "daemon",
    "difftime",
    "dlclose",
    "dlerror",
    "dlopen",
    "dlsym",
    "doff",
    "double_hex_str",
    "dprintf",
    "drand48",
    "drand48_r",
    "__drem",
    "drem",
    "__dremf",
    "dremf",
    "__dreml",
    "dreml",
    "dup",
    "dup2",
    "dysize",
    "ecvt",
    "ecvt_r",
    "endusershell",
    "erand48",
    "erand48_r",
    "__erf",
    "__erfc",
    "erfc",
    "__erfcf",
    "erfcf",
    "__erfcl",
    "erfcl",
    "__erff",
    "erff",
    "__erfl",
    "erfl",
    "__errno_location",
    "execl",
    "execle",
    "execlp",
    "execv",
    "execve",
    "execvp",
    "_exit",
    "_Exit",
    "__exp",
    "__exp2",
    "exp2",
    "__exp2f",
    "exp2f",
    "__exp2l",
    "exp2l",
    "__expf",
    "expf",
    "__expl",
    "expl",
    "explicit_bzero",
    "__expm1",
    "expm1",
    "__expm1f",
    "expm1f",
    "__expm1l",
    "expm1l",
    "__fabs",
    "fabs",
    "__fabsf",
    "fabsf",
    "__fabsl",
    "fabsl",
    "faccessat",
    "fatal_error",
    "fchdir",
    "fchmod",
    "fchmodat",
    "fchown",
    "fchownat",
    "fclose",
    "fcvt",
    "fcvt_r",
    "fdatasync",
    "__fdim",
    "fdim",
    "__fdimf",
    "fdimf",
    "__fdiml",
    "fdiml",
    "fdopen",
    "feof",
    "feof_unlocked",
    "ferror",
    "ferror_unlocked",
    "fexecve",
    "fflush",
    "fflush_unlocked",
    "ffsl",
    "ffsll",
    "fgetc",
    "fgetc_unlocked",
    "fgetpos",
    "fgets",
    "fgetwc",
    "fgetws",
    "fileno",
    "fileno_unlocked",
    "__finite",
    "finite",
    "__finitef",
    "finitef",
    "__finitel",
    "finitel",
    "flockfile",
    "__floor",
    "__floorf",
    "floorf",
    "__floorl",
    "floorl",
    "__fma",
    "fma",
    "__fmaf",
    "fmaf",
    "__fmal",
    "fmal",
    "__fmax",
    "fmax",
    "__fmaxf",
    "fmaxf",
    "__fmaxl",
    "fmaxl",
    "fmemopen",
    "__fmin",
    "fmin",
    "__fminf",
    "fminf",
    "__fminl",
    "fminl",
    "__fmod",
    "fmod",
    "__fmodf",
    "fmodf",
    "__fmodl",
    "fmodl",
    "fopen",
    "fopencookie",
    "for_all_intervals",
    "fork",
    "for_some_intervals",
    "fpathconf",
    "__fpclassify",
    "__fpclassifyf",
    "__fpclassifyl",
    "fphex_strtod",
    "fprintf",
    "fputc",
    "fputc_unlocked",
    "fputs",
    "fputwc",
    "fputws",
    "frags_extract",
    "frags_extract_alloc",
    "frags_extract_slice",
    "frags_extract_slice_alloc",
    "fread",
    "fread_unlocked",
    "free_interval",
    "freopen",
    "__frexp",
    "frexp",
    "__frexpf",
    "frexpf",
    "__frexpl",
    "frexpl",
    "fscanf",
    "fscanf1",
    "fseek",
    "fseeko",
    "fsetpos",
    "fstat",
    "fstatat",
    "fsync",
    "ftell",
    "ftello",
    "ftruncate",
    "ftrylockfile",
    "funlockfile",
    "futimens",
    "futimes",
    "fwide",
    "fwprintf",
    "fwrite",
    "fwrite_unlocked",
    "fwscanf",
    "fwscanf1",
    "__gamma",
    "gamma",
    "__gammaf",
    "gammaf",
    "__gammal",
    "gammal",
    "gcvt",
    "genrand_destroy",
    "genrand_double",
    "genrand_init",
    "genrand_init_array",
    "genrand_range",
    "genrand_restore",
    "genrand_serialization",
    "genrand_uint32",
    "genrand_uint64",
    "get_bit",
    "getc",
    "getchar",
    "getchar_unlocked",
    "getc_unlocked",
    "getcwd",
    "__getdelim",
    "getdelim",
    "getdomainname",
    "getdtablesize",
    "getegid",
    "getentropy",
    "getenv",
    "geteuid",
    "getgid",
    "getgroups",
    "get_higher_interval_ptr",
    "gethostid",
    "gethostname",
    "get_interval_ptr",
    "get_interval_vector",
    "get_interval_vector_and_range",
    "getitimer",
    "getline",
    "getloadavg",
    "getlogin",
    "getlogin_r",
    "get_lower_interval_ptr",
    "getopt",
    "getpagesize",
    "getpass",
    "getpeername",
    "__getpgid",
    "getpgid",
    "getpgrp",
    "getpid",
    "getppid",
    "getsid",
    "getsockname",
    "getsockopt",
    "getsubopt",
    "gettimeofday",
    "getuid",
    "getusershell",
    "get_vtoptarg",
    "get_vtopterr",
    "get_vtoptind",
    "get_vtoptopt",
    "getw",
    "getwc",
    "getwchar",
    "getwd",
    "gmtime",
    "gmtime_r",
    "guest_phys_valid",
    "__hypot",
    "hypot",
    "__hypotf",
    "hypotf",
    "__hypotl",
    "hypotl",
    "IDP_GetVersion",
    "if_freenameindex",
    "if_indextoname",
    "if_nameindex",
    "if_nametoindex",
    "__ilogb",
    "ilogb",
    "__ilogbf",
    "ilogbf",
    "__ilogbl",
    "ilogbl",
    "imaxabs",
    "imaxdiv",
    "initialize_encoding",
    "insert_interval",
    "int128_as_string",
    "int128_div_int64",
    "int128_from_double",
    "int128_to_double",
    "interned",
    "interval_set_iter_next",
    "interval_set_new_iter",
    "inverse_endian",
    "isalnum",
    "isalnum_l",
    "isalpha",
    "isalpha_l",
    "isascii",
    "isatty",
    "isblank",
    "isblank_l",
    "iscntrl",
    "iscntrl_l",
    "isdigit",
    "isdigit_l",
    "__iseqsig",
    "__iseqsigf",
    "__iseqsigl",
    "isfdtype",
    "isgraph",
    "isgraph_l",
    "__isinf",
    "isinf",
    "__isinff",
    "isinff",
    "__isinfl",
    "isinfl",
    "islower",
    "islower_l",
    "__isnan",
    "isnan",
    "__isnanf",
    "isnanf",
    "__isnanl",
    "isnanl",
    "isprint",
    "isprint_l",
    "ispunct",
    "ispunct_l",
    "__issignaling",
    "__issignalingf",
    "__issignalingl",
    "isspace",
    "isspace_l",
    "isupper",
    "isupper_l",
    "isxdigit",
    "isxdigit_l",
    "__j0",
    "j0",
    "__j0f",
    "j0f",
    "__j0l",
    "j0l",
    "__j1",
    "j1",
    "__j1f",
    "j1f",
    "__j1l",
    "j1l",
    "__jn",
    "jn",
    "__jnf",
    "jnf",
    "__jnl",
    "jnl",
    "jrand48",
    "jrand48_r",
    "l64a",
    "labs",
    "lchmod",
    "lchown",
    "lcong48",
    "lcong48_r",
    "__ldexp",
    "ldexp",
    "__ldexpf",
    "ldexpf",
    "__ldexpl",
    "ldexpl",
    "ldiv",
    "__lgamma",
    "lgamma",
    "__lgammaf",
    "lgammaf",
    "__lgammaf_r",
    "lgammaf_r",
    "__lgammal",
    "lgammal",
    "__lgammal_r",
    "lgammal_r",
    "__lgamma_r",
    "lgamma_r",
    "linkat",
    "llabs",
    "lldiv",
    "__llrint",
    "llrint",
    "__llrintf",
    "llrintf",
    "__llrintl",
    "llrintl",
    "__llround",
    "llround",
    "__llroundf",
    "llroundf",
    "__llroundl",
    "llroundl",
    "localtime",
    "localtime_r",
    "lockf",
    "__log",
    "__log10",
    "log10",
    "__log10f",
    "log10f",
    "__log10l",
    "log10l",
    "__log1p",
    "log1p",
    "__log1pf",
    "log1pf",
    "__log1pl",
    "log1pl",
    "__log2",
    "log2",
    "__log2f",
    "log2f",
    "__log2l",
    "log2l",
    "__logb",
    "logb",
    "__logbf",
    "logbf",
    "__logbl",
    "logbl",
    "__logf",
    "logf",
    "__logl",
    "logl",
    "lrand48",
    "lrand48_r",
    "__lrint",
    "lrint",
    "__lrintf",
    "lrintf",
    "__lrintl",
    "lrintl",
    "__lround",
    "lround",
    "__lroundf",
    "lroundf",
    "__lroundl",
    "lroundl",
    "lseek",
    "lstat",
    "lutimes",
    "mblen",
    "__mbrlen",
    "mbrlen",
    "mbrtowc",
    "mbsinit",
    "mbsnrtowcs",
    "mbsrtowcs",
    "mbstowcs",
    "mbtowc",
    "memccpy",
    "memchr",
    "memcmp",
    "__memcmpeq",
    "mem_hier_on_fetch",
    "memmem",
    "memmove",
    "__mempcpy",
    "mempcpy",
    "memset",
    "mkdir",
    "mkdirat",
    "mkdtemp",
    "mkfifo",
    "mkfifoat",
    "mknod",
    "mknodat",
    "mkstemp",
    "mkstemps",
    "mktemp",
    "mktime",
    "__modf",
    "modf",
    "__modff",
    "modff",
    "__modfl",
    "modfl",
    "mrand48",
    "mrand48_r",
    "__nan",
    "nan",
    "__nanf",
    "nanf",
    "__nanl",
    "nanl",
    "nanosleep",
    "__nearbyint",
    "nearbyint",
    "__nearbyintf",
    "nearbyintf",
    "__nearbyintl",
    "nearbyintl",
    "new_bitfield_1",
    "new_interval",
    "__nextafter",
    "nextafter",
    "__nextafterf",
    "nextafterf",
    "__nextafterl",
    "nextafterl",
    "__nexttoward",
    "nexttoward",
    "__nexttowardf",
    "nexttowardf",
    "__nexttowardl",
    "nexttowardl",
    "nice",
    "non_coherent",
    "nrand48",
    "nrand48_r",
    "null_arg_error",
    "on_exit",
    "open_memstream",
    "open_wmemstream",
    "os_absolutify",
    "os_access",
    "os_basename",
    "os_chdir",
    "os_clean_path",
    "os_close_descriptors",
    "os_copy",
    "os_create_unique_autoremoved_file",
    "os_current_time",
    "os_current_time_us",
    "os_describe_last_dlerror",
    "os_describe_last_error",
    "os_describe_last_socket_error",
    "os_dir_contains_path",
    "os_dirname",
    "os_dladdr",
    "os_dlclose",
    "os_dllookup",
    "os_dlopen",
    "os_fclose",
    "os_file_exists",
    "os_fopen",
    "os_ftruncate",
    "os_getcwd",
    "os_getcwd_nice",
    "os_get_file_size",
    "os_gethostname",
    "os_get_last_error",
    "os_get_library_path",
    "os_getpid",
    "os_get_process_binary_path",
    "os_get_thread_name",
    "os_get_user_name",
    "os_gmtime",
    "os_host_ncpus",
    "os_host_phys_mem_size",
    "os_host_virt_mem_size",
    "os_initialize_sockets",
    "os_isabs",
    "os_isdir",
    "os_isfile",
    "os_is_same_file",
    "os_last_error_was_error",
    "os_last_socket_error",
    "os_listdir",
    "os_lseek",
    "os_make_readable_path",
    "os_make_sparse",
    "os_millisleep",
    "os_mkdir",
    "os_mmap",
    "os_munmap",
    "os_normalize_path",
    "os_open",
    "os_open_vararg",
    "os_path_expand_user",
    "os_path_join",
    "os_pread",
    "os_pwrite",
    "os_quote_filename",
    "os_realpath",
    "os_remove",
    "os_rename",
    "os_rmdir",
    "os_rmenv",
    "os_setenv",
    "os_set_socket_blocking",
    "os_set_socket_nodelay",
    "os_set_socket_non_blocking",
    "os_set_socket_reuseaddr",
    "os_set_thread_name",
    "os_socket_close",
    "os_socket_connect",
    "os_socket_get_status",
    "os_socket_read",
    "os_socket_write",
    "os_socket_write_non_blocking",
    "os_stat",
    "os_strptime",
    "os_timegm",
    "os_user_cpu_time_us",
    "__overflow",
    "pathconf",
    "pause",
    "pclose",
    "perror",
    "popen",
    "posix_memalign",
    "__pow",
    "__powf",
    "powf",
    "__powl",
    "powl",
    "pread",
    "prof_data_add",
    "prof_data_clear",
    "prof_data_create",
    "prof_data_delete",
    "prof_data_get",
    "prof_data_granularity_log2",
    "prof_data_iter_addr",
    "prof_data_iter_next",
    "prof_data_load",
    "prof_data_new_iter",
    "prof_data_save",
    "prof_data_set",
    "pselect",
    "psh",
    "pthread_atfork",
    "pthread_attr_destroy",
    "pthread_attr_getdetachstate",
    "pthread_attr_getguardsize",
    "pthread_attr_getinheritsched",
    "pthread_attr_getschedparam",
    "pthread_attr_getschedpolicy",
    "pthread_attr_getscope",
    "pthread_attr_getstack",
    "pthread_attr_getstackaddr",
    "pthread_attr_getstacksize",
    "pthread_attr_init",
    "pthread_attr_setdetachstate",
    "pthread_attr_setguardsize",
    "pthread_attr_setinheritsched",
    "pthread_attr_setschedparam",
    "pthread_attr_setschedpolicy",
    "pthread_attr_setscope",
    "pthread_attr_setstack",
    "pthread_attr_setstackaddr",
    "pthread_attr_setstacksize",
    "pthread_barrierattr_destroy",
    "pthread_barrierattr_getpshared",
    "pthread_barrierattr_init",
    "pthread_barrierattr_setpshared",
    "pthread_barrier_destroy",
    "pthread_barrier_init",
    "pthread_barrier_wait",
    "pthread_cancel",
    "pthread_condattr_destroy",
    "pthread_condattr_getclock",
    "pthread_condattr_getpshared",
    "pthread_condattr_init",
    "pthread_condattr_setclock",
    "pthread_condattr_setpshared",
    "pthread_cond_broadcast",
    "pthread_cond_destroy",
    "pthread_cond_init",
    "pthread_cond_signal",
    "pthread_cond_timedwait",
    "pthread_cond_wait",
    "pthread_create",
    "pthread_detach",
    "pthread_equal",
    "pthread_exit",
    "pthread_getcpuclockid",
    "pthread_getschedparam",
    "pthread_getspecific",
    "pthread_join",
    "pthread_key_create",
    "pthread_key_delete",
    "pthread_mutexattr_destroy",
    "pthread_mutexattr_getprioceiling",
    "pthread_mutexattr_getprotocol",
    "pthread_mutexattr_getpshared",
    "pthread_mutexattr_getrobust",
    "pthread_mutexattr_gettype",
    "pthread_mutexattr_init",
    "pthread_mutexattr_setprioceiling",
    "pthread_mutexattr_setprotocol",
    "pthread_mutexattr_setpshared",
    "pthread_mutexattr_setrobust",
    "pthread_mutexattr_settype",
    "pthread_mutex_consistent",
    "pthread_mutex_destroy",
    "pthread_mutex_getprioceiling",
    "pthread_mutex_init",
    "pthread_mutex_lock",
    "pthread_mutex_setprioceiling",
    "pthread_mutex_timedlock",
    "pthread_mutex_trylock",
    "pthread_mutex_unlock",
    "pthread_once",
    "__pthread_register_cancel",
    "pthread_rwlockattr_destroy",
    "pthread_rwlockattr_getkind_np",
    "pthread_rwlockattr_getpshared",
    "pthread_rwlockattr_init",
    "pthread_rwlockattr_setkind_np",
    "pthread_rwlockattr_setpshared",
    "pthread_rwlock_destroy",
    "pthread_rwlock_init",
    "pthread_rwlock_rdlock",
    "pthread_rwlock_timedrdlock",
    "pthread_rwlock_timedwrlock",
    "pthread_rwlock_tryrdlock",
    "pthread_rwlock_trywrlock",
    "pthread_rwlock_unlock",
    "pthread_rwlock_wrlock",
    "pthread_self",
    "pthread_setcancelstate",
    "pthread_setcanceltype",
    "pthread_setschedparam",
    "pthread_setschedprio",
    "pthread_setspecific",
    "pthread_spin_destroy",
    "pthread_spin_init",
    "pthread_spin_lock",
    "pthread_spin_trylock",
    "pthread_spin_unlock",
    "pthread_testcancel",
    "__pthread_unregister_cancel",
    "__pthread_unwind_next",
    "putchar_unlocked",
    "putc_unlocked",
    "putenv",
    "putw",
    "putwc",
    "putwchar",
    "pwrite",
    "*Py*",
    "*PY*",
    "qecvt",
    "qecvt_r",
    "qfcvt",
    "qfcvt_r",
    "qgcvt",
    "qsort",
    "quick_exit",
    "random",
    "random_r",
    "rand_r",
    "readlink",
    "readlinkat",
    "realloc",
    "reallocarray",
    "realpath",
    "recv",
    "recvfrom",
    "recvmsg",
    "__remainder",
    "remainder",
    "__remainderf",
    "remainderf",
    "__remainderl",
    "remainderl",
    "remove_interval",
    "__remquo",
    "remquo",
    "__remquof",
    "remquof",
    "__remquol",
    "remquol",
    "renameat",
    "res1",
    "res2",
    "revoke",
    "rindex",
    "__rint",
    "__rintf",
    "__rintl",
    "rintl",
    "rmdir",
    "__round",
    "__roundf",
    "roundf",
    "__roundl",
    "roundl",
    "rpmatch",
    "sb_addesc",
    "sb_addfmt",
    "sb_detach",
    "sb_fmt",
    "sb_free",
    "sb_new",
    "sb_newf",
    "sb_readline",
    "sb_realloc",
    "sbrk",
    "sb_vaddfmt",
    "sb_vfmt",
    "sb_write",
    "__scalb",
    "scalb",
    "__scalbf",
    "scalbf",
    "__scalbl",
    "scalbl",
    "__scalbln",
    "scalbln",
    "__scalblnf",
    "scalblnf",
    "__scalblnl",
    "scalblnl",
    "__scalbn",
    "scalbn",
    "__scalbnf",
    "scalbnf",
    "__scalbnl",
    "scalbnl",
    "scanf1",
    "__sched_cpualloc",
    "__sched_cpucount",
    "__sched_cpufree",
    "sched_getparam",
    "sched_get_priority_max",
    "sched_get_priority_min",
    "sched_getscheduler",
    "sched_rr_get_interval",
    "sched_setparam",
    "sched_setscheduler",
    "sched_yield",
    "seed48",
    "seed48_r",
    "sendmsg",
    "sendto",
    "set_access_linear",
    "set_ack",
    "set_ascii",
    "set_atomic",
    "set_atst",
    "set_bit",
    "set_block_STC",
    "setbuf",
    "setbuffer",
    "set_cache_coherency",
    "set_compact",
    "set_device_type",
    "set_doff",
    "setdomainname",
    "setegid",
    "setenv",
    "seteuid",
    "set_fault_as_if_write",
    "set_fin",
    "setgid",
    "set_guest_phys_valid",
    "sethostid",
    "sethostname",
    "set_ignore",
    "set_inner_allocation_hint",
    "set_inner_cacheability",
    "set_inner_transcience_hint",
    "set_inquiry",
    "set_interned",
    "set_inverse_endian",
    "set_io",
    "setitimer",
    "set_kind",
    "setlinebuf",
    "setlogin",
    "set_may_stall",
    "set_mem_hier_on_fetch",
    "set_memory_type",
    "set_non_coherent",
    "set_outer_allocation_hint",
    "set_outer_cacheability",
    "set_outer_shareable",
    "set_outer_transcience_hint",
    "set_page_cross",
    "setpgid",
    "setpgrp",
    "set_psh",
    "set_ready",
    "setregid",
    "set_reissue",
    "set_res1",
    "set_res2",
    "setreuid",
    "set_rst",
    "set_secsid",
    "set_shareable",
    "set_sid",
    "setsid",
    "setsockopt",
    "set_ssid",
    "set_ssidv",
    "setstate",
    "setstate_r",
    "set_syn",
    "set_tcpi_rcv_wscale",
    "set_tcpi_snd_wscale",
    "set_th_off",
    "set_th_x2",
    "settimeofday",
    "setuid",
    "set_urg",
    "set_use_page_cache",
    "setusershell",
    "setvbuf",
    "__signbit",
    "__signbitf",
    "__signbitl",
    "signed_divide_128_by_64",
    "__significand",
    "significand",
    "__significandf",
    "significandf",
    "__significandl",
    "significandl",
    "__sigsetjmp",
    "__sin",
    "__sinf",
    "sinf",
    "__sinh",
    "sinh",
    "__sinhf",
    "sinhf",
    "__sinhl",
    "sinhl",
    "__sinl",
    "sinl",
    "snprintf",
    "sockatmark",
    "socketpair",
    "sprintf",
    "__sqrt",
    "sqrt",
    "__sqrtf",
    "sqrtf",
    "__sqrtl",
    "sqrtl",
    "srand",
    "srand48",
    "srand48_r",
    "srandom",
    "srandom_r",
    "sscanf",
    "sscanf1",
    "__stpcpy",
    "stpcpy",
    "__stpncpy",
    "stpncpy",
    "strcasecmp",
    "strcasecmp_l",
    "strcasestr",
    "strcat",
    "strchr",
    "strchrnul",
    "strcmp",
    "strcoll",
    "strcoll_l",
    "strcpy",
    "strcspn",
    "strdup",
    "strerror",
    "strerror_l",
    "strerror_r",
    "strftime",
    "strftime_l",
    "strlcat",
    "strlcpy",
    "strlen",
    "strncasecmp",
    "strncasecmp_l",
    "strncat",
    "strncmp",
    "strncpy",
    "strndup",
    "strnlen",
    "strpbrk",
    "strrchr",
    "strsep",
    "strsignal",
    "strspn",
    "strstr",
    "strtod",
    "strtof",
    "strtoimax",
    "strtok",
    "__strtok_r",
    "strtok_r",
    "strtol",
    "strtold",
    "strtoll",
    "strtoq",
    "strtoul",
    "strtoull",
    "strtoumax",
    "strtouq",
    "str_vec_add",
    "str_vec_add_stealing",
    "str_vec_find",
    "str_vec_free",
    "str_vec_remove",
    "str_vec_sort",
    "strxfrm",
    "strxfrm_l",
    "swprintf",
    "swscanf",
    "swscanf1",
    "symlink",
    "symlinkat",
    "syscall",
    "sysconf",
    "__tan",
    "__tanf",
    "tanf",
    "__tanh",
    "tanh",
    "__tanhf",
    "tanhf",
    "__tanhl",
    "tanhl",
    "__tanl",
    "tanl",
    "tcgetpgrp",
    "tcpi_rcv_wscale",
    "tcpi_snd_wscale",
    "tcsetpgrp",
    "tempnam",
    "__tgamma",
    "tgamma",
    "__tgammaf",
    "tgammaf",
    "__tgammal",
    "tgammal",
    "th_off",
    "th_x2",
    "timegm",
    "timelocal",
    "timer_create",
    "timer_delete",
    "timer_getoverrun",
    "timer_gettime",
    "timer_settime",
    "timespec_get",
    "tmpfile",
    "tmpnam",
    "tmpnam_r",
    "toascii",
    "_tolower",
    "tolower",
    "__tolower_l",
    "tolower_l",
    "touch_interval",
    "_toupper",
    "toupper",
    "__toupper_l",
    "toupper_l",
    "__trunc",
    "__truncf",
    "truncf",
    "__truncl",
    "truncl",
    "ttyname",
    "ttyname_r",
    "ttyslot",
    "tzset",
    "ualarm",
    "__uflow",
    "umask",
    "ungetc",
    "ungetwc",
    "unlink",
    "unlinkat",
    "unsetenv",
    "unsigned_gcd",
    "unsigned_multiply_rational",
    "urg",
    "use_page_cache",
    "usleep",
    "utimensat",
    "utimes",
    "valloc",
    "vasprintf",
    "vdprintf",
    "vfork",
    "vfprintf",
    "vfscanf",
    "vfscanf1",
    "vfwprintf",
    "vfwscanf",
    "vfwscanf1",
    "vhangup",
    "vprintf",
    "vscanf",
    "vscanf1",
    "vsnprintf",
    "vsprintf",
    "vsscanf",
    "vsscanf1",
    "vswprintf",
    "vswscanf",
    "vswscanf1",
    "vwprintf",
    "vwscanf",
    "vwscanf1",
    "wcpcpy",
    "wcpncpy",
    "wcrtomb",
    "wcscasecmp",
    "wcscasecmp_l",
    "wcscat",
    "wcschr",
    "wcscmp",
    "wcscoll",
    "wcscoll_l",
    "wcscpy",
    "wcscspn",
    "wcsdup",
    "wcsftime",
    "wcslcat",
    "wcslcpy",
    "wcslen",
    "wcsncasecmp",
    "wcsncasecmp_l",
    "wcsncat",
    "wcsncmp",
    "wcsncpy",
    "wcsnlen",
    "wcsnrtombs",
    "wcspbrk",
    "wcsrchr",
    "wcsrtombs",
    "wcsspn",
    "wcsstr",
    "wcstod",
    "wcstof",
    "wcstoimax",
    "wcstok",
    "wcstol",
    "wcstold",
    "wcstoll",
    "wcstombs",
    "wcstoul",
    "wcstoull",
    "wcstoumax",
    "wcsxfrm",
    "wcsxfrm_l",
    "wctob",
    "wctomb",
    "wmemchr",
    "wmemcmp",
    "wmemcpy",
    "wmemmove",
    "wmemset",
    "wprintf",
    "wscanf",
    "wscanf1",
    "__y0",
    "y0",
    "__y0f",
    "y0f",
    "__y0l",
    "y0l",
    "__y1",
    "__y1f",
    "y1f",
    "__y1l",
    "y1l",
    "__yn",
    "__ynf",
    "ynf",
    "__ynl",
    "ynl",
];
