# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "fuzzer"
categories.workspace = true
description = "Target Software Fuzzer for SIMICS Command-Line interface"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
default-run = "fuzzer"

[dependencies]
anyhow = { workspace = true }
libafl = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simics = { workspace = true }
version-tools = { workspace = true }
libafl_bolts = { workspace = true }
tsffs = { workspace = true }
versions = { workspace = true }

clap = { version = "4.3.0", features = ["derive", "string", "wrap_help"] }
derive_builder = "0.12.0"
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.15"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
strum_macros = "0.25.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "ansi",
    "json",
    "fmt",
    "std",
    "env-filter",
] }
goblin = "0.7.1"

[build-dependencies]
anyhow = { workspace = true }

[features]
default = ["link"]
link = []
