//! Messages generated by the module

use serde::{Deserialize, Serialize};

use crate::module::{config::InitializedConfig, stop_reason::StopReason};

#[derive(Debug, Serialize, Deserialize)]
pub enum ModuleMessage {
    /// Mesage
    Initialized(InitializedConfig),
    /// Message indicating ready to run
    Ready,
    /// Message indicating stopped and the reason why, for example a crash, normal run finished,
    /// or some error occurred.
    Stopped(StopReason),
}
