//! Messages generated by the module

use crate::{config::OutputConfig, stops::StopReason};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum ModuleMessage {
    /// Mesage
    Initialized(OutputConfig),
    /// Message indicating ready to run
    Ready,
    /// Message indicating stopped and the reason why, for example a crash, normal run finished,
    /// or some error occurred.
    Stopped(StopReason),
}
