# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tmp-dir"
categories.workspace = true
description = "Temporary directory utilities with sane default directory permissions"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
derive_builder = "0.12.0"
rand = "0.8.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2.147"
