# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ispm-wrapper"
version = "0.1.0"
authors = ["Rowan Hart <rowan.hart@intel.com>"]
edition = "2021"
description = "Wrappers for Intel Simics Package Manager commands"
documentation = ""
readme = "../README.md"
homepage = ""
repository = ""
license = "Apache-2.0"
keywords = ["simics", "simulator", "intel", "x86", "risc", "modeling"]
categories = [
    "simulation",
    "virtualization",
    "hardware-support",
    "api-bindings",
    "emulators",
]


[dependencies]
anyhow = "1.0.80"
command-ext = "0.1.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
typed-builder = "0.18.1"
versions = { version = "6.1.0", features = ["serde"] }
