// Copyright (C) 2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

//! Messages generated by the client

use crate::config::InputConfig;

#[derive(Debug, Clone)]
/// Messages from the client
pub enum ClientMessage {
    /// Initialize event, the fuzzer signals the module to initialize itself with
    /// a given set of global campaign settings
    Initialize(InputConfig),
    /// The fuzzer signals the module to run with a given input of bytes
    Run(Vec<u8>),
    /// The fuzzer signals the module to reset to the start snapshot
    Reset,
    /// The fuzzer signals the module to stop execution and exit
    Exit,
}
