# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "simics"
categories.workspace = true
description = "Tools for embedding SIMICS in Rust applications"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
raw-cstr = { workspace = true }
simics-macro = { workspace = true, optional = true }
simics-api-sys = { workspace = true }
ispm-wrapper = { workspace = true }
clap = { version = "4.3.0", features = ["derive"] }
num = "0.4.0"
num-traits = "0.2.15"
paste = "1.0.12"
regex = "1.8.3"
tracing = "0.1.37"
walkdir = "2.3.3"
thiserror = "1.0.49"
anyhow.workspace = true
typed-builder = "0.18.0"
ordered-float = "4.1.1"

[features]
default = ["derive", "link"]
derive = ["simics-macro"]
link = ["simics-api-sys/link"]

[build-dependencies]
anyhow.workspace = true
prettyplease = "0.2.15"
simics-api-sys.workspace = true
simics-codegen.workspace = true
simics-macro.workspace = true
syn = "2.0.38"
version-tools.workspace = true
