extern crate num_traits;
use anyhow::{Context, Error, Result};
use num_derive::FromPrimitive;

#[derive(FromPrimitive)]
#[repr(u16)]
/// A Magic value that can be generated by a target as part of a "Magic Instruction" (cpuid with
/// a specific leaf on x86) and passed to SIMICS through the `Core_Magic_Instruction` HAP
pub enum Magic {
    /// Magic value that the target has reached its stop location
    Stop = 0x4242,
    /// Magic value that the target has reached its start location
    Start = 0x4343,
}

impl TryFrom<u16> for Magic {
    type Error = Error;

    /// Try to convert a u16 value to a known `Magic` value
    fn try_from(value: u16) -> Result<Self> {
        num::FromPrimitive::from_u16(value)
            .context(format!("Could not convert value {} to Magic", value))
    }
}
