# -*- Makefile -*-
# Simics module makefile for the Pipe manager module.
#

MODULE_CLASSES = confuse_ll

SRC_FILES = confuse-ll.c
#PYTHON_FILES := module_load.py simics_start.py

SIMICS_API := latest
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)
