---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007:
    indent: 2 # Unordered list indentation
MD013:
    line_length: 88 # Line length 80 is far too short
    ignore_code_blocks: true
    tables: false
    code_blocks: false
MD026:
    punctuation: ".,;:!。，；:" # List of not allowed
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a heading
MD041: false # HTML can be at the top of the file for the image and such
MD045: false # Do not require alt text

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
