# -*- Makefile -*-
# Simics module makefile for the Pipe manager module.
#

MODULE_CLASSES = confuse_dio

SRC_FILES = confuse-dio.c
#PYTHON_FILES := module_load.py simics_start.py

EXTRA_MODULE_VPATH = magic-pipe-interface

SIMICS_API := latest
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)
