#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_CLASSES = afl_branch_tracer
SRC_FILES += afl-branch-tracer.c

SIMICS_API := latest
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)

