# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tsffs"
categories.workspace = true
description = "Loadable SIMICS module for TSFFS fuzzer"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = { workspace = true }
simics = { workspace = true }
ffi-macro = { workspace = true }
raw-cstr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simics-api-macro = { workspace = true }
libafl = { workspace = true }
libafl_bolts = { workspace = true }

c2rust-bitfields = "0.18.0"
const_format = "0.2.30"
crc32fast = "1.3.2"
derive_builder = "0.12.0"
num = "0.4.0"
num-derive = "0.4.0"
num-traits = "0.2.15"
rand = "0.8.5"
rng = "0.1.0"
rust-fsm = "0.6.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "ansi",
    "json",
    "fmt",
    "std",
] }
yaxpeax-arch = "0.2.7"
yaxpeax-x86 = "1.2.0"
c2rust-bitfields-derive = "0.18.0"
