# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tsffs"
categories.workspace = true
description = "Loadable SIMICS module for TSFFS fuzzer"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
anyhow = { workspace = true }
ffi-macro = { workspace = true }
libafl = { workspace = true }
libafl_bolts = { workspace = true }
libafl_targets = { workspace = true }
raw-cstr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simics = { workspace = true, features = ["link"] }
simics-macro = { workspace = true }

c2rust-bitfields = "0.18.0"
const_format = "0.2.30"
crc32fast = "1.3.2"
derive_builder = "0.12.0"
num = "0.4.0"
num-derive = "0.4.0"
num-traits = "0.2.15"
rand = "0.8.5"
rng = "0.1.0"
rust-fsm = "0.6.1"
yaxpeax-arch = "0.2.7"
yaxpeax-x86 = "1.2.0"
c2rust-bitfields-derive = "0.18.0"
typed-builder = "0.17.0"
getters.workspace = true
ordered-float = "4.1.1"
serde_json.workspace = true
goblin = "0.7.1"
# yaxpeax-riscv = { git = "https://github.com/novafacing/yaxpeax-riscv", version = "0.1.0", features = [
#     "serde",
# ], rev = "0c5ab07a279692ce16978029d842735e106c4411" }
yaxpeax-riscv = { path = "/home/rhart/hub/yaxpeax-riscv" }

[dev-dependencies]
