# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tsffs"
categories.workspace = true
description = "Loadable SIMICS module for TSFFS fuzzer"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
anyhow = { workspace = true }
ffi-macro = { workspace = true }
libafl = { workspace = true }
libafl_bolts = { workspace = true }
libafl_targets = { workspace = true }
raw-cstr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simics = { workspace = true, features = ["link"] }
simics-macro = { workspace = true }
yaxpeax-arch = "0.2.7"
yaxpeax-x86 = "1.2.0"
typed-builder = "0.18.0"
getters.workspace = true
serde_json.workspace = true
goblin = "0.7.1"
yaxpeax-riscv = { git = "https://github.com/novafacing/yaxpeax-riscv", version = "0.1.0", features = [
    "serde",
], rev = "696eb047208e4d3c903654aa557a42071c466e71" }
crc32fast = "1.3.2"

[dev-dependencies]
