# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "simics-macro"
categories.workspace = true
description = "High level SIMICS API proc macros"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = { version = "2.0.15", features = ["full"] }
proc-macro2 = "1.0.56"
proc-macro-error = "1.0.4"
darling = "0.20.3"
indoc = "2.0.4"

[dev-dependencies]

anyhow.workspace = true
raw-cstr.workspace = true
trybuild = { version = "1.0.80", features = ["diff"] }


[features]
